/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *dialog_add_troup;
  GtkWidget *dialog_edit_troup;
  GtkWidget *dialog_event;
  GtkWidget *dialog_milk;
  GtkWidget *window_troup;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  dialog_add_troup = create_dialog_add_troup ();
  //gtk_widget_show (dialog_add_troup);
  dialog_edit_troup = create_dialog_edit_troup ();
  //gtk_widget_show (dialog_edit_troup);
  dialog_event = create_dialog_event ();
  //gtk_widget_show (dialog_event);
  dialog_milk = create_dialog_milk ();
  //gtk_widget_show (dialog_milk);
  window_troup = create_window_troup ();
  gtk_widget_show (window_troup);

  gtk_main ();
  return 0;
}

