/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed8;
  GtkWidget *reference;
  GtkWidget *commentaire;
  GtkObject *day_adj;
  GtkWidget *day;
  GtkObject *month_adj;
  GtkWidget *month;
  GtkObject *year_adj;
  GtkWidget *year;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkWidget *label56;
  GtkWidget *label19;
  GtkObject *spinbutton_j_engrais_adj;
  GtkWidget *spinbutton_j_engrais;
  GtkObject *spinbutton_m_engrais_adj;
  GtkWidget *spinbutton_m_engrais;
  GtkObject *spinbutton_a_engrais_adj;
  GtkWidget *spinbutton_a_engrais;
  GtkWidget *label97;
  GtkWidget *label99;
  GtkWidget *label98;
  GtkWidget *label57;
  GtkObject *taille_jour_adj;
  GtkWidget *taille_jour;
  GtkObject *taille_mois_adj;
  GtkWidget *taille_mois;
  GtkObject *taille_annee_adj;
  GtkWidget *taille_annee;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label_reference;
  GtkWidget *label_unite;
  GtkWidget *label127;
  GtkWidget *quantit__;
  GtkWidget *label58;
  GtkWidget *annee;
  GtkWidget *mois;
  GtkWidget *jour;
  GtkWidget *label55;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label136;
  GtkWidget *label137;
  GtkWidget *label138;
  GtkWidget *label17;
  GtkWidget *engrais_chimique;
  GtkWidget *unite_plante;
  GtkWidget *Usage;
  GtkWidget *label34;
  GtkWidget *label134;
  GtkWidget *label133;
  GtkWidget *label143;
  GtkWidget *label135;
  GtkWidget *label_quantite;
  GtkWidget *radiobutton_taille_mois;
  GSList *radiobutton_taille_mois_group = NULL;
  GtkWidget *radiobutton_taille_semaine;
  GtkWidget *radiobutton_taille_annee;
  GtkWidget *taille;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog2 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog_ajout_plante"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed8, TRUE, TRUE, 0);

  reference = gtk_entry_new ();
  gtk_widget_show (reference);
  gtk_fixed_put (GTK_FIXED (fixed8), reference, 328, 8);
  gtk_widget_set_size_request (reference, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (reference), 8226);

  commentaire = gtk_entry_new ();
  gtk_widget_show (commentaire);
  gtk_fixed_put (GTK_FIXED (fixed8), commentaire, 264, 408);
  gtk_widget_set_size_request (commentaire, 344, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (commentaire), 8226);

  day_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  day = gtk_spin_button_new (GTK_ADJUSTMENT (day_adj), 1, 0);
  gtk_widget_show (day);
  gtk_fixed_put (GTK_FIXED (fixed8), day, 448, 56);
  gtk_widget_set_size_request (day, 48, 24);

  month_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  month = gtk_spin_button_new (GTK_ADJUSTMENT (month_adj), 1, 0);
  gtk_widget_show (month);
  gtk_fixed_put (GTK_FIXED (fixed8), month, 496, 56);
  gtk_widget_set_size_request (month, 48, 24);

  year_adj = gtk_adjustment_new (2016, 2015, 9999, 1, 10, 0);
  year = gtk_spin_button_new (GTK_ADJUSTMENT (year_adj), 1, 0);
  gtk_widget_show (year);
  gtk_fixed_put (GTK_FIXED (fixed8), year, 544, 56);
  gtk_widget_set_size_request (year, 64, 24);

  spinbutton10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton10, 168, 56);
  gtk_widget_set_size_request (spinbutton10, 56, 24);

  spinbutton11_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton11, 168, 152);
  gtk_widget_set_size_request (spinbutton11, 56, 24);

  label56 = gtk_label_new (_("Commentaire :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed8), label56, 120, 408);
  gtk_widget_set_size_request (label56, 112, 24);

  label19 = gtk_label_new (_("Engrais chimique  :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed8), label19, 0, 256);
  gtk_widget_set_size_request (label19, 152, 32);

  spinbutton_j_engrais_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_j_engrais = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_j_engrais_adj), 1, 0);
  gtk_widget_show (spinbutton_j_engrais);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_j_engrais, 504, 256);
  gtk_widget_set_size_request (spinbutton_j_engrais, 56, 24);

  spinbutton_m_engrais_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_m_engrais = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_m_engrais_adj), 1, 0);
  gtk_widget_show (spinbutton_m_engrais);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_m_engrais, 560, 256);
  gtk_widget_set_size_request (spinbutton_m_engrais, 56, 24);

  spinbutton_a_engrais_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  spinbutton_a_engrais = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_a_engrais_adj), 1, 0);
  gtk_widget_show (spinbutton_a_engrais);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_a_engrais, 616, 256);
  gtk_widget_set_size_request (spinbutton_a_engrais, 60, 24);

  label97 = gtk_label_new (_("jour"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed8), label97, 504, 240);
  gtk_widget_set_size_request (label97, 49, 17);

  label99 = gtk_label_new (_("annee"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed8), label99, 624, 240);
  gtk_widget_set_size_request (label99, 49, 17);

  label98 = gtk_label_new (_("mois"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed8), label98, 560, 240);
  gtk_widget_set_size_request (label98, 49, 17);

  label57 = gtk_label_new (_("Arrosage"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed8), label57, 24, 208);
  gtk_widget_set_size_request (label57, 128, 24);

  taille_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  taille_jour = gtk_spin_button_new (GTK_ADJUSTMENT (taille_jour_adj), 1, 0);
  gtk_widget_show (taille_jour);
  gtk_fixed_put (GTK_FIXED (fixed8), taille_jour, 336, 352);
  gtk_widget_set_size_request (taille_jour, 60, 27);

  taille_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  taille_mois = gtk_spin_button_new (GTK_ADJUSTMENT (taille_mois_adj), 1, 0);
  gtk_widget_show (taille_mois);
  gtk_fixed_put (GTK_FIXED (fixed8), taille_mois, 400, 352);
  gtk_widget_set_size_request (taille_mois, 60, 27);

  taille_annee_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  taille_annee = gtk_spin_button_new (GTK_ADJUSTMENT (taille_annee_adj), 1, 0);
  gtk_widget_show (taille_annee);
  gtk_fixed_put (GTK_FIXED (fixed8), taille_annee, 464, 352);
  gtk_widget_set_size_request (taille_annee, 60, 27);

  label100 = gtk_label_new (_("jour"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed8), label100, 336, 336);
  gtk_widget_set_size_request (label100, 57, 17);

  label101 = gtk_label_new (_("mois"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed8), label101, 400, 336);
  gtk_widget_set_size_request (label101, 57, 17);

  label102 = gtk_label_new (_("annee"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed8), label102, 464, 336);
  gtk_widget_set_size_request (label102, 57, 17);

  label103 = gtk_label_new (_("date de taille"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed8), label103, 176, 352);
  gtk_widget_set_size_request (label103, 136, 24);

  label_reference = gtk_label_new ("");
  gtk_widget_show (label_reference);
  gtk_fixed_put (GTK_FIXED (fixed8), label_reference, 512, 8);
  gtk_widget_set_size_request (label_reference, 72, 25);

  label_unite = gtk_label_new ("");
  gtk_widget_show (label_unite);
  gtk_fixed_put (GTK_FIXED (fixed8), label_unite, 632, 56);
  gtk_widget_set_size_request (label_unite, 40, 24);

  label127 = gtk_label_new ("");
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed8), label127, 328, 8);
  gtk_widget_set_size_request (label127, 384, 24);

  quantit__ = gtk_label_new (_("Quantit\303\251  :"));
  gtk_widget_show (quantit__);
  gtk_fixed_put (GTK_FIXED (fixed8), quantit__, 48, 56);
  gtk_widget_set_size_request (quantit__, 120, 24);

  label58 = gtk_label_new (_("Quantit\303\251\nr\303\251colt\303\251e "));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed8), label58, 56, 128);
  gtk_widget_set_size_request (label58, 104, 72);

  annee = gtk_label_new (_("annee"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed8), annee, 552, 40);
  gtk_widget_set_size_request (annee, 49, 17);

  mois = gtk_label_new (_("mois"));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed8), mois, 496, 40);
  gtk_widget_set_size_request (mois, 49, 17);

  jour = gtk_label_new (_("jour"));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed8), jour, 440, 40);
  gtk_widget_set_size_request (jour, 56, 16);

  label55 = gtk_label_new (_("Unit\303\251 :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed8), label55, 256, 96);
  gtk_widget_set_size_request (label55, 48, 24);

  spinbutton12_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton12, 448, 152);
  gtk_widget_set_size_request (spinbutton12, 48, 24);

  spinbutton13_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton13, 448, 152);
  gtk_widget_set_size_request (spinbutton13, 48, 24);

  spinbutton14_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton14, 448, 152);
  gtk_widget_set_size_request (spinbutton14, 48, 24);

  spinbutton15_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton15, 496, 152);
  gtk_widget_set_size_request (spinbutton15, 48, 24);

  spinbutton16_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton16, 544, 152);
  gtk_widget_set_size_request (spinbutton16, 64, 24);

  label136 = gtk_label_new (_("jour"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed8), label136, 440, 136);
  gtk_widget_set_size_request (label136, 57, 17);

  label137 = gtk_label_new (_("mois"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed8), label137, 488, 136);
  gtk_widget_set_size_request (label137, 57, 17);

  label138 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed8), label138, 544, 136);
  gtk_widget_set_size_request (label138, 57, 17);

  label17 = gtk_label_new (_("Reference  :\n"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed8), label17, 152, 8);
  gtk_widget_set_size_request (label17, 176, 24);

  engrais_chimique = gtk_combo_box_entry_new_text ();
  gtk_widget_show (engrais_chimique);
  gtk_fixed_put (GTK_FIXED (fixed8), engrais_chimique, 152, 256);
  gtk_widget_set_size_request (engrais_chimique, 192, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_chimique), _("Type x"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_chimique), _("Type y"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_chimique), _("Type z"));

  unite_plante = gtk_combo_box_entry_new_text ();
  gtk_widget_show (unite_plante);
  gtk_fixed_put (GTK_FIXED (fixed8), unite_plante, 320, 96);
  gtk_widget_set_size_request (unite_plante, 181, 24);
  gtk_container_set_border_width (GTK_CONTAINER (unite_plante), 3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_plante), "---");
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_plante), "G");
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_plante), "KG");

  Usage = gtk_label_new (_("date d'utilisation"));
  gtk_widget_show (Usage);
  gtk_fixed_put (GTK_FIXED (fixed8), Usage, 360, 256);
  gtk_widget_set_size_request (Usage, 144, 24);

  label34 = gtk_label_new (_("Date de plantation "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 312, 56);
  gtk_widget_set_size_request (label34, 144, 24);

  label134 = gtk_label_new ("");
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed8), label134, 40, 384);
  gtk_widget_set_size_request (label134, 648, 16);

  label133 = gtk_label_new ("");
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed8), label133, 16, 280);
  gtk_widget_set_size_request (label133, 696, 56);

  label143 = gtk_label_new ("");
  gtk_widget_show (label143);
  gtk_fixed_put (GTK_FIXED (fixed8), label143, 288, 184);
  gtk_widget_set_size_request (label143, 408, 16);

  label135 = gtk_label_new (_("Date de recolte"));
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed8), label135, 240, 152);
  gtk_widget_set_size_request (label135, 208, 24);

  label_quantite = gtk_label_new ("");
  gtk_widget_show (label_quantite);
  gtk_fixed_put (GTK_FIXED (fixed8), label_quantite, 224, 56);
  gtk_widget_set_size_request (label_quantite, 48, 24);

  radiobutton_taille_mois = gtk_radio_button_new_with_mnemonic (NULL, _("Hebdomadaire"));
  gtk_widget_show (radiobutton_taille_mois);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_taille_mois, 328, 208);
  gtk_widget_set_size_request (radiobutton_taille_mois, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_taille_mois), radiobutton_taille_mois_group);
  radiobutton_taille_mois_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_taille_mois));

  radiobutton_taille_semaine = gtk_radio_button_new_with_mnemonic (NULL, _("Quotidien"));
  gtk_widget_show (radiobutton_taille_semaine);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_taille_semaine, 168, 208);
  gtk_widget_set_size_request (radiobutton_taille_semaine, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_taille_semaine), radiobutton_taille_mois_group);
  radiobutton_taille_mois_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_taille_semaine));

  radiobutton_taille_annee = gtk_radio_button_new_with_mnemonic (NULL, _("Mensuel"));
  gtk_widget_show (radiobutton_taille_annee);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_taille_annee, 512, 208);
  gtk_widget_set_size_request (radiobutton_taille_annee, 104, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_taille_annee), radiobutton_taille_mois_group);
  radiobutton_taille_mois_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_taille_annee));

  taille = gtk_check_button_new_with_mnemonic (_("taille"));
  gtk_widget_show (taille);
  gtk_fixed_put (GTK_FIXED (fixed8), taille, 40, 352);
  gtk_widget_set_size_request (taille, 118, 24);

  dialog_action_area1 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) radiobutton_taille_mois, "clicked",
                    G_CALLBACK (on_radiobutton_taille_mois_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_taille_semaine, "clicked",
                    G_CALLBACK (on_radiobutton_taille_semaine_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_taille_annee, "clicked",
                    G_CALLBACK (on_radiobutton_taille_annee_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog2, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (dialog2, reference, "reference");
  GLADE_HOOKUP_OBJECT (dialog2, commentaire, "commentaire");
  GLADE_HOOKUP_OBJECT (dialog2, day, "day");
  GLADE_HOOKUP_OBJECT (dialog2, month, "month");
  GLADE_HOOKUP_OBJECT (dialog2, year, "year");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (dialog2, label56, "label56");
  GLADE_HOOKUP_OBJECT (dialog2, label19, "label19");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton_j_engrais, "spinbutton_j_engrais");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton_m_engrais, "spinbutton_m_engrais");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton_a_engrais, "spinbutton_a_engrais");
  GLADE_HOOKUP_OBJECT (dialog2, label97, "label97");
  GLADE_HOOKUP_OBJECT (dialog2, label99, "label99");
  GLADE_HOOKUP_OBJECT (dialog2, label98, "label98");
  GLADE_HOOKUP_OBJECT (dialog2, label57, "label57");
  GLADE_HOOKUP_OBJECT (dialog2, taille_jour, "taille_jour");
  GLADE_HOOKUP_OBJECT (dialog2, taille_mois, "taille_mois");
  GLADE_HOOKUP_OBJECT (dialog2, taille_annee, "taille_annee");
  GLADE_HOOKUP_OBJECT (dialog2, label100, "label100");
  GLADE_HOOKUP_OBJECT (dialog2, label101, "label101");
  GLADE_HOOKUP_OBJECT (dialog2, label102, "label102");
  GLADE_HOOKUP_OBJECT (dialog2, label103, "label103");
  GLADE_HOOKUP_OBJECT (dialog2, label_reference, "label_reference");
  GLADE_HOOKUP_OBJECT (dialog2, label_unite, "label_unite");
  GLADE_HOOKUP_OBJECT (dialog2, label127, "label127");
  GLADE_HOOKUP_OBJECT (dialog2, quantit__, "quantit__");
  GLADE_HOOKUP_OBJECT (dialog2, label58, "label58");
  GLADE_HOOKUP_OBJECT (dialog2, annee, "annee");
  GLADE_HOOKUP_OBJECT (dialog2, mois, "mois");
  GLADE_HOOKUP_OBJECT (dialog2, jour, "jour");
  GLADE_HOOKUP_OBJECT (dialog2, label55, "label55");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (dialog2, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (dialog2, label136, "label136");
  GLADE_HOOKUP_OBJECT (dialog2, label137, "label137");
  GLADE_HOOKUP_OBJECT (dialog2, label138, "label138");
  GLADE_HOOKUP_OBJECT (dialog2, label17, "label17");
  GLADE_HOOKUP_OBJECT (dialog2, engrais_chimique, "engrais_chimique");
  GLADE_HOOKUP_OBJECT (dialog2, unite_plante, "unite_plante");
  GLADE_HOOKUP_OBJECT (dialog2, Usage, "Usage");
  GLADE_HOOKUP_OBJECT (dialog2, label34, "label34");
  GLADE_HOOKUP_OBJECT (dialog2, label134, "label134");
  GLADE_HOOKUP_OBJECT (dialog2, label133, "label133");
  GLADE_HOOKUP_OBJECT (dialog2, label143, "label143");
  GLADE_HOOKUP_OBJECT (dialog2, label135, "label135");
  GLADE_HOOKUP_OBJECT (dialog2, label_quantite, "label_quantite");
  GLADE_HOOKUP_OBJECT (dialog2, radiobutton_taille_mois, "radiobutton_taille_mois");
  GLADE_HOOKUP_OBJECT (dialog2, radiobutton_taille_semaine, "radiobutton_taille_semaine");
  GLADE_HOOKUP_OBJECT (dialog2, radiobutton_taille_annee, "radiobutton_taille_annee");
  GLADE_HOOKUP_OBJECT (dialog2, taille, "taille");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog2, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog2, okbutton1, "okbutton1");

  return dialog2;
}

GtkWidget*
create_dialog5 (void)
{
  GtkWidget *dialog5;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed12;
  GtkWidget *label53;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  dialog5 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog5), _("dialog5"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog5), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog5), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog5)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed12, TRUE, TRUE, 0);

  label53 = gtk_label_new (_("Suppression valid\303\251e"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed12), label53, 24, 24);
  gtk_widget_set_size_request (label53, 152, 17);

  dialog_action_area2 = GTK_DIALOG (dialog5)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog5), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton2, "clicked",
                    G_CALLBACK (on_okbutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, dialog5, "dialog5");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog5, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (dialog5, label53, "label53");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog5, okbutton2, "okbutton2");

  return dialog5;
}

GtkWidget*
create_dialog6 (void)
{
  GtkWidget *dialog6;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed13;
  GtkWidget *Modification_valid__e;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton3;

  dialog6 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog6), _("dialog6"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog6), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog6), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog6)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed13, TRUE, TRUE, 0);

  Modification_valid__e = gtk_label_new (_("Modification valid\303\251e"));
  gtk_widget_show (Modification_valid__e);
  gtk_fixed_put (GTK_FIXED (fixed13), Modification_valid__e, 40, 40);
  gtk_widget_set_size_request (Modification_valid__e, 160, 16);

  dialog_action_area3 = GTK_DIALOG (dialog6)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog6), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton3, "clicked",
                    G_CALLBACK (on_okbutton3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, dialog6, "dialog6");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog6, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (dialog6, Modification_valid__e, "Modification_valid__e");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog6, okbutton3, "okbutton3");

  return dialog6;
}

GtkWidget*
create_Gestion_des_plantations (void)
{
  GtkWidget *Gestion_des_plantations;
  GtkWidget *notebook1;
  GtkWidget *fixed16;
  GtkWidget *recherche_plante_entry;
  GtkWidget *recherche_plante;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label81;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_plante;
  GtkWidget *actualiser_plante;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label52;
  GtkWidget *supprimer_plante;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;
  GtkWidget *modifier_plante;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *ajouter_plante;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *ajouter;
  GtkWidget *label79;
  GtkWidget *fixed20;
  GtkWidget *calendar2;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview_precipitation;
  GtkObject *precipitation_adj;
  GtkWidget *precipitation;
  GtkWidget *pr__cipitation;
  GtkWidget *ajout_precipitation;
  GtkWidget *image17;
  GtkWidget *actualiser2;
  GtkWidget *image16;
  GtkWidget *Affiche_TB;
  GtkWidget *label124;

  Gestion_des_plantations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_des_plantations, 1270, 500);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_plantations), _("Gestion_des_plantations"));
  gtk_window_set_default_size (GTK_WINDOW (Gestion_des_plantations), 1270, 500);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Gestion_des_plantations), notebook1);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed16);

  recherche_plante_entry = gtk_entry_new ();
  gtk_widget_show (recherche_plante_entry);
  gtk_fixed_put (GTK_FIXED (fixed16), recherche_plante_entry, 48, 48);
  gtk_widget_set_size_request (recherche_plante_entry, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (recherche_plante_entry), 8226);

  recherche_plante = gtk_button_new ();
  gtk_widget_show (recherche_plante);
  gtk_fixed_put (GTK_FIXED (fixed16), recherche_plante, 232, 48);
  gtk_widget_set_size_request (recherche_plante, 120, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (recherche_plante), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox15), label81, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed16), scrolledwindow1, 48, 88);
  gtk_widget_set_size_request (scrolledwindow1, 1184, 320);

  treeview_plante = gtk_tree_view_new ();
  gtk_widget_show (treeview_plante);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_plante);

  actualiser_plante = gtk_button_new ();
  gtk_widget_show (actualiser_plante);
  gtk_fixed_put (GTK_FIXED (fixed16), actualiser_plante, 1104, 56);
  gtk_widget_set_size_request (actualiser_plante, 120, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (actualiser_plante), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox13), label52, FALSE, FALSE, 0);

  supprimer_plante = gtk_button_new ();
  gtk_widget_show (supprimer_plante);
  gtk_fixed_put (GTK_FIXED (fixed16), supprimer_plante, 1104, 408);
  gtk_widget_set_size_request (supprimer_plante, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (supprimer_plante), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  modifier_plante = gtk_button_new ();
  gtk_widget_show (modifier_plante);
  gtk_fixed_put (GTK_FIXED (fixed16), modifier_plante, 984, 408);
  gtk_widget_set_size_request (modifier_plante, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (modifier_plante), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  ajouter_plante = gtk_button_new ();
  gtk_widget_show (ajouter_plante);
  gtk_fixed_put (GTK_FIXED (fixed16), ajouter_plante, 864, 408);
  gtk_widget_set_size_request (ajouter_plante, 120, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_plante), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  ajouter = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouter);
  gtk_box_pack_start (GTK_BOX (hbox1), ajouter, FALSE, FALSE, 0);

  label79 = gtk_label_new (_("table des plantations"));
  gtk_widget_show (label79);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label79);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed20);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed20), calendar2, 96, 0);
  gtk_widget_set_size_request (calendar2, 232, 224);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed20), scrolledwindow3, 96, 232);
  gtk_widget_set_size_request (scrolledwindow3, 688, 240);

  treeview_precipitation = gtk_tree_view_new ();
  gtk_widget_show (treeview_precipitation);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview_precipitation);

  precipitation_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  precipitation = gtk_spin_button_new (GTK_ADJUSTMENT (precipitation_adj), 1, 0);
  gtk_widget_show (precipitation);
  gtk_fixed_put (GTK_FIXED (fixed20), precipitation, 536, 88);
  gtk_widget_set_size_request (precipitation, 60, 27);

  pr__cipitation = gtk_label_new (_("pr\303\251cipitaion"));
  gtk_widget_show (pr__cipitation);
  gtk_fixed_put (GTK_FIXED (fixed20), pr__cipitation, 392, 88);
  gtk_widget_set_size_request (pr__cipitation, 120, 24);

  ajout_precipitation = gtk_button_new ();
  gtk_widget_show (ajout_precipitation);
  gtk_fixed_put (GTK_FIXED (fixed20), ajout_precipitation, 480, 136);
  gtk_widget_set_size_request (ajout_precipitation, 74, 29);

  image17 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (ajout_precipitation), image17);

  actualiser2 = gtk_button_new ();
  gtk_widget_show (actualiser2);
  gtk_fixed_put (GTK_FIXED (fixed20), actualiser2, 728, 192);
  gtk_widget_set_size_request (actualiser2, 42, 32);

  image16 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (actualiser2), image16);

  Affiche_TB = gtk_button_new_with_mnemonic (_("Afficher tableau de bord"));
  gtk_widget_show (Affiche_TB);
  gtk_fixed_put (GTK_FIXED (fixed20), Affiche_TB, 712, 0);
  gtk_widget_set_size_request (Affiche_TB, 200, 24);

  label124 = gtk_label_new (_("calendrier des pr\303\251cipitations"));
  gtk_widget_show (label124);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label124);

  g_signal_connect ((gpointer) recherche_plante, "clicked",
                    G_CALLBACK (on_recherche_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_plante, "row_activated",
                    G_CALLBACK (on_treeview_plante_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiser_plante, "clicked",
                    G_CALLBACK (on_actualiser_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_plante, "clicked",
                    G_CALLBACK (on_supprimer_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_plante, "clicked",
                    G_CALLBACK (on_modifier_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_plante, "clicked",
                    G_CALLBACK (on_ajouter_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_precipitation, "clicked",
                    G_CALLBACK (on_ajout_precipitation_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser2, "clicked",
                    G_CALLBACK (on_actualiser2_clicked),
                    NULL);
  g_signal_connect ((gpointer) Affiche_TB, "clicked",
                    G_CALLBACK (on_Affiche_TB_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_plantations, Gestion_des_plantations, "Gestion_des_plantations");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, recherche_plante_entry, "recherche_plante_entry");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, recherche_plante, "recherche_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image15, "image15");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label81, "label81");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, treeview_plante, "treeview_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, actualiser_plante, "actualiser_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label52, "label52");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, supprimer_plante, "supprimer_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image2, "image2");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label11, "label11");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, modifier_plante, "modifier_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image3, "image3");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label12, "label12");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, ajouter_plante, "ajouter_plante");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image1, "image1");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label79, "label79");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, treeview_precipitation, "treeview_precipitation");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, precipitation, "precipitation");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, pr__cipitation, "pr__cipitation");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, ajout_precipitation, "ajout_precipitation");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image17, "image17");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, actualiser2, "actualiser2");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, image16, "image16");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, Affiche_TB, "Affiche_TB");
  GLADE_HOOKUP_OBJECT (Gestion_des_plantations, label124, "label124");

  return Gestion_des_plantations;
}

GtkWidget*
create_dialog9 (void)
{
  GtkWidget *dialog9;
  GtkWidget *vbox4;
  GtkWidget *fixed19;
  GtkWidget *reference_modif;
  GtkWidget *commentaire_modif;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkObject *quantite_modif_adj;
  GtkWidget *quantite_modif;
  GtkObject *quantite_recolte_modif_adj;
  GtkWidget *quantite_recolte_modif;
  GtkWidget *label104;
  GtkWidget *label114;
  GtkObject *jour_engrais_modif_adj;
  GtkWidget *jour_engrais_modif;
  GtkObject *mois_engrais_modif_adj;
  GtkWidget *mois_engrais_modif;
  GtkObject *annee_engrais_modif_adj;
  GtkWidget *annee_engrais_modif;
  GtkWidget *label115;
  GtkWidget *label116;
  GtkWidget *label117;
  GtkWidget *label118;
  GtkWidget *label119;
  GtkObject *jour_taille_modif_adj;
  GtkWidget *jour_taille_modif;
  GtkObject *mois_taille_modif_adj;
  GtkWidget *mois_taille_modif;
  GtkObject *annee_taille_modif_adj;
  GtkWidget *annee_taille_modif;
  GtkWidget *label120;
  GtkWidget *label121;
  GtkWidget *label122;
  GtkWidget *label123;
  GtkWidget *engrais_modif;
  GtkWidget *label_ref_modif;
  GtkWidget *label131;
  GtkWidget *label112;
  GtkWidget *label106;
  GtkWidget *label109;
  GtkWidget *label108;
  GtkWidget *label107;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkWidget *label142;
  GtkWidget *label140;
  GtkWidget *label141;
  GtkWidget *label139;
  GtkWidget *unite_modif;
  GtkWidget *label113;
  GtkWidget *label144;
  GtkWidget *label145;
  GtkWidget *label146;
  GtkWidget *arrosage1;
  GSList *arrosage1_group = NULL;
  GtkWidget *arrosage_mois;
  GtkWidget *arrosage_annee;
  GtkWidget *checkbutton2;
  GtkWidget *hbuttonbox4;
  GtkWidget *button20;
  GtkWidget *button21;

  dialog9 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog9), _("Modifier_plante"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog9), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog9), FALSE);

  vbox4 = GTK_DIALOG (dialog9)->vbox;
  gtk_widget_show (vbox4);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_box_pack_start (GTK_BOX (vbox4), fixed19, TRUE, TRUE, 0);

  reference_modif = gtk_entry_new ();
  gtk_widget_show (reference_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), reference_modif, 296, 8);
  gtk_widget_set_size_request (reference_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (reference_modif), 8226);

  commentaire_modif = gtk_entry_new ();
  gtk_widget_show (commentaire_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), commentaire_modif, 264, 408);
  gtk_widget_set_size_request (commentaire_modif, 344, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (commentaire_modif), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed19), jour, 416, 56);
  gtk_widget_set_size_request (jour, 48, 24);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed19), mois, 464, 56);
  gtk_widget_set_size_request (mois, 48, 24);

  annee_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 0);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed19), annee, 512, 56);
  gtk_widget_set_size_request (annee, 64, 24);

  quantite_modif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  quantite_modif = gtk_spin_button_new (GTK_ADJUSTMENT (quantite_modif_adj), 1, 0);
  gtk_widget_show (quantite_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), quantite_modif, 152, 56);
  gtk_widget_set_size_request (quantite_modif, 56, 24);

  quantite_recolte_modif_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  quantite_recolte_modif = gtk_spin_button_new (GTK_ADJUSTMENT (quantite_recolte_modif_adj), 1, 0);
  gtk_widget_show (quantite_recolte_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), quantite_recolte_modif, 152, 152);
  gtk_widget_set_size_request (quantite_recolte_modif, 56, 24);

  label104 = gtk_label_new (_("Commentaire :"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed19), label104, 120, 408);
  gtk_widget_set_size_request (label104, 112, 24);

  label114 = gtk_label_new (_("Engrais chimique  :"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed19), label114, 0, 256);
  gtk_widget_set_size_request (label114, 152, 32);

  jour_engrais_modif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_engrais_modif = gtk_spin_button_new (GTK_ADJUSTMENT (jour_engrais_modif_adj), 1, 0);
  gtk_widget_show (jour_engrais_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), jour_engrais_modif, 504, 256);
  gtk_widget_set_size_request (jour_engrais_modif, 56, 24);

  mois_engrais_modif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_engrais_modif = gtk_spin_button_new (GTK_ADJUSTMENT (mois_engrais_modif_adj), 1, 0);
  gtk_widget_show (mois_engrais_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), mois_engrais_modif, 560, 256);
  gtk_widget_set_size_request (mois_engrais_modif, 56, 24);

  annee_engrais_modif_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  annee_engrais_modif = gtk_spin_button_new (GTK_ADJUSTMENT (annee_engrais_modif_adj), 1, 0);
  gtk_widget_show (annee_engrais_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), annee_engrais_modif, 616, 256);
  gtk_widget_set_size_request (annee_engrais_modif, 60, 24);

  label115 = gtk_label_new (_("date d'utilisation"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed19), label115, 360, 256);
  gtk_widget_set_size_request (label115, 144, 24);

  label116 = gtk_label_new (_("jour"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed19), label116, 504, 240);
  gtk_widget_set_size_request (label116, 49, 17);

  label117 = gtk_label_new (_("annee"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed19), label117, 624, 240);
  gtk_widget_set_size_request (label117, 49, 17);

  label118 = gtk_label_new (_("mois"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed19), label118, 560, 240);
  gtk_widget_set_size_request (label118, 49, 17);

  label119 = gtk_label_new (_("Arrosage"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed19), label119, 24, 208);
  gtk_widget_set_size_request (label119, 128, 24);

  jour_taille_modif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_taille_modif = gtk_spin_button_new (GTK_ADJUSTMENT (jour_taille_modif_adj), 1, 0);
  gtk_widget_show (jour_taille_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), jour_taille_modif, 336, 352);
  gtk_widget_set_size_request (jour_taille_modif, 60, 27);

  mois_taille_modif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_taille_modif = gtk_spin_button_new (GTK_ADJUSTMENT (mois_taille_modif_adj), 1, 0);
  gtk_widget_show (mois_taille_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), mois_taille_modif, 400, 352);
  gtk_widget_set_size_request (mois_taille_modif, 60, 27);

  annee_taille_modif_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  annee_taille_modif = gtk_spin_button_new (GTK_ADJUSTMENT (annee_taille_modif_adj), 1, 0);
  gtk_widget_show (annee_taille_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), annee_taille_modif, 464, 352);
  gtk_widget_set_size_request (annee_taille_modif, 60, 27);

  label120 = gtk_label_new (_("jour"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed19), label120, 336, 336);
  gtk_widget_set_size_request (label120, 57, 17);

  label121 = gtk_label_new (_("mois"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed19), label121, 400, 336);
  gtk_widget_set_size_request (label121, 57, 17);

  label122 = gtk_label_new (_("annee"));
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed19), label122, 464, 336);
  gtk_widget_set_size_request (label122, 57, 17);

  label123 = gtk_label_new (_("date de taille"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed19), label123, 176, 352);
  gtk_widget_set_size_request (label123, 136, 24);

  engrais_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (engrais_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), engrais_modif, 152, 256);
  gtk_widget_set_size_request (engrais_modif, 197, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_modif), _("Type x"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_modif), _("Type y"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (engrais_modif), _("Type z"));

  label_ref_modif = gtk_label_new ("");
  gtk_widget_show (label_ref_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), label_ref_modif, 336, 8);
  gtk_widget_set_size_request (label_ref_modif, 336, 24);

  label131 = gtk_label_new ("");
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed19), label131, 296, 56);
  gtk_widget_set_size_request (label131, 48, 24);

  label112 = gtk_label_new (_("Quantit\303\251  :"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed19), label112, 48, 56);
  gtk_widget_set_size_request (label112, 120, 24);

  label106 = gtk_label_new (_("Quantit\303\251\nr\303\251colt\303\251e "));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed19), label106, 56, 128);
  gtk_widget_set_size_request (label106, 104, 72);

  label109 = gtk_label_new (_("jour"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed19), label109, 408, 40);
  gtk_widget_set_size_request (label109, 56, 16);

  label108 = gtk_label_new (_("mois"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed19), label108, 456, 40);
  gtk_widget_set_size_request (label108, 49, 17);

  label107 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed19), label107, 512, 40);
  gtk_widget_set_size_request (label107, 49, 17);

  label110 = gtk_label_new (_("Date de plantation "));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed19), label110, 264, 56);
  gtk_widget_set_size_request (label110, 144, 24);

  label111 = gtk_label_new (_("Unit\303\251 :"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed19), label111, 192, 96);
  gtk_widget_set_size_request (label111, 48, 24);

  spinbutton17_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton17, 416, 152);
  gtk_widget_set_size_request (spinbutton17, 48, 24);

  spinbutton18_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_show (spinbutton18);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton18, 464, 152);
  gtk_widget_set_size_request (spinbutton18, 48, 24);

  spinbutton19_adj = gtk_adjustment_new (1, 2015, 9999, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 0);
  gtk_widget_show (spinbutton19);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton19, 512, 152);
  gtk_widget_set_size_request (spinbutton19, 64, 24);

  label142 = gtk_label_new (_("jour"));
  gtk_widget_show (label142);
  gtk_fixed_put (GTK_FIXED (fixed19), label142, 408, 136);
  gtk_widget_set_size_request (label142, 57, 17);

  label140 = gtk_label_new (_("mois"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed19), label140, 456, 136);
  gtk_widget_set_size_request (label140, 57, 17);

  label141 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed19), label141, 512, 136);
  gtk_widget_set_size_request (label141, 57, 17);

  label139 = gtk_label_new (_("Date de recolte"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed19), label139, 248, 152);
  gtk_widget_set_size_request (label139, 168, 24);

  unite_modif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (unite_modif);
  gtk_fixed_put (GTK_FIXED (fixed19), unite_modif, 240, 96);
  gtk_widget_set_size_request (unite_modif, 181, 24);
  gtk_container_set_border_width (GTK_CONTAINER (unite_modif), 3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_modif), "---");
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_modif), "G");
  gtk_combo_box_append_text (GTK_COMBO_BOX (unite_modif), "KG");

  label113 = gtk_label_new (_("Reference  :\n"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed19), label113, 120, 8);
  gtk_widget_set_size_request (label113, 176, 24);

  label144 = gtk_label_new ("");
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (fixed19), label144, 240, 176);
  gtk_widget_set_size_request (label144, 440, 16);

  label145 = gtk_label_new ("");
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed19), label145, 40, 304);
  gtk_widget_set_size_request (label145, 640, 16);

  label146 = gtk_label_new ("");
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed19), label146, 8, 384);
  gtk_widget_set_size_request (label146, 664, 16);

  arrosage1 = gtk_radio_button_new_with_mnemonic (NULL, _("Quotidien"));
  gtk_widget_show (arrosage1);
  gtk_fixed_put (GTK_FIXED (fixed19), arrosage1, 168, 208);
  gtk_widget_set_size_request (arrosage1, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (arrosage1), arrosage1_group);
  arrosage1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (arrosage1));

  arrosage_mois = gtk_radio_button_new_with_mnemonic (NULL, _("Hebdomadaire"));
  gtk_widget_show (arrosage_mois);
  gtk_fixed_put (GTK_FIXED (fixed19), arrosage_mois, 328, 208);
  gtk_widget_set_size_request (arrosage_mois, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (arrosage_mois), arrosage1_group);
  arrosage1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (arrosage_mois));

  arrosage_annee = gtk_radio_button_new_with_mnemonic (NULL, _("Mensuel"));
  gtk_widget_show (arrosage_annee);
  gtk_fixed_put (GTK_FIXED (fixed19), arrosage_annee, 496, 208);
  gtk_widget_set_size_request (arrosage_annee, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (arrosage_annee), arrosage1_group);
  arrosage1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (arrosage_annee));

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("taille"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed19), checkbutton2, 40, 352);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  hbuttonbox4 = GTK_DIALOG (dialog9)->action_area;
  gtk_widget_show (hbuttonbox4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);

  button20 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button20);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog9), button20, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  button21 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button21);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog9), button21, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) arrosage1, "clicked",
                    G_CALLBACK (on_arrosage1_clicked),
                    NULL);
  g_signal_connect ((gpointer) arrosage_mois, "clicked",
                    G_CALLBACK (on_arrosage_mois_clicked),
                    NULL);
  g_signal_connect ((gpointer) arrosage_annee, "clicked",
                    G_CALLBACK (on_arrosage_annee_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog9, dialog9, "dialog9");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog9, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog9, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (dialog9, reference_modif, "reference_modif");
  GLADE_HOOKUP_OBJECT (dialog9, commentaire_modif, "commentaire_modif");
  GLADE_HOOKUP_OBJECT (dialog9, jour, "jour");
  GLADE_HOOKUP_OBJECT (dialog9, mois, "mois");
  GLADE_HOOKUP_OBJECT (dialog9, annee, "annee");
  GLADE_HOOKUP_OBJECT (dialog9, quantite_modif, "quantite_modif");
  GLADE_HOOKUP_OBJECT (dialog9, quantite_recolte_modif, "quantite_recolte_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label104, "label104");
  GLADE_HOOKUP_OBJECT (dialog9, label114, "label114");
  GLADE_HOOKUP_OBJECT (dialog9, jour_engrais_modif, "jour_engrais_modif");
  GLADE_HOOKUP_OBJECT (dialog9, mois_engrais_modif, "mois_engrais_modif");
  GLADE_HOOKUP_OBJECT (dialog9, annee_engrais_modif, "annee_engrais_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label115, "label115");
  GLADE_HOOKUP_OBJECT (dialog9, label116, "label116");
  GLADE_HOOKUP_OBJECT (dialog9, label117, "label117");
  GLADE_HOOKUP_OBJECT (dialog9, label118, "label118");
  GLADE_HOOKUP_OBJECT (dialog9, label119, "label119");
  GLADE_HOOKUP_OBJECT (dialog9, jour_taille_modif, "jour_taille_modif");
  GLADE_HOOKUP_OBJECT (dialog9, mois_taille_modif, "mois_taille_modif");
  GLADE_HOOKUP_OBJECT (dialog9, annee_taille_modif, "annee_taille_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label120, "label120");
  GLADE_HOOKUP_OBJECT (dialog9, label121, "label121");
  GLADE_HOOKUP_OBJECT (dialog9, label122, "label122");
  GLADE_HOOKUP_OBJECT (dialog9, label123, "label123");
  GLADE_HOOKUP_OBJECT (dialog9, engrais_modif, "engrais_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label_ref_modif, "label_ref_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label131, "label131");
  GLADE_HOOKUP_OBJECT (dialog9, label112, "label112");
  GLADE_HOOKUP_OBJECT (dialog9, label106, "label106");
  GLADE_HOOKUP_OBJECT (dialog9, label109, "label109");
  GLADE_HOOKUP_OBJECT (dialog9, label108, "label108");
  GLADE_HOOKUP_OBJECT (dialog9, label107, "label107");
  GLADE_HOOKUP_OBJECT (dialog9, label110, "label110");
  GLADE_HOOKUP_OBJECT (dialog9, label111, "label111");
  GLADE_HOOKUP_OBJECT (dialog9, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (dialog9, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (dialog9, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (dialog9, label142, "label142");
  GLADE_HOOKUP_OBJECT (dialog9, label140, "label140");
  GLADE_HOOKUP_OBJECT (dialog9, label141, "label141");
  GLADE_HOOKUP_OBJECT (dialog9, label139, "label139");
  GLADE_HOOKUP_OBJECT (dialog9, unite_modif, "unite_modif");
  GLADE_HOOKUP_OBJECT (dialog9, label113, "label113");
  GLADE_HOOKUP_OBJECT (dialog9, label144, "label144");
  GLADE_HOOKUP_OBJECT (dialog9, label145, "label145");
  GLADE_HOOKUP_OBJECT (dialog9, label146, "label146");
  GLADE_HOOKUP_OBJECT (dialog9, arrosage1, "arrosage1");
  GLADE_HOOKUP_OBJECT (dialog9, arrosage_mois, "arrosage_mois");
  GLADE_HOOKUP_OBJECT (dialog9, arrosage_annee, "arrosage_annee");
  GLADE_HOOKUP_OBJECT (dialog9, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog9, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (dialog9, button20, "button20");
  GLADE_HOOKUP_OBJECT (dialog9, button21, "button21");

  return dialog9;
}

GtkWidget*
create_dialog10 (void)
{
  GtkWidget *dialog10;
  GtkWidget *vbox5;
  GtkWidget *fixed21;
  GtkWidget *label125;
  GtkWidget *hbuttonbox5;
  GtkWidget *valid_supp;

  dialog10 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog10), _("dialog5"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog10), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog10), FALSE);

  vbox5 = GTK_DIALOG (dialog10)->vbox;
  gtk_widget_show (vbox5);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_box_pack_start (GTK_BOX (vbox5), fixed21, TRUE, TRUE, 0);

  label125 = gtk_label_new (_("Suppression valid\303\251e"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed21), label125, 32, 32);
  gtk_widget_set_size_request (label125, 152, 17);

  hbuttonbox5 = GTK_DIALOG (dialog10)->action_area;
  gtk_widget_show (hbuttonbox5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_END);

  valid_supp = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (valid_supp);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog10), valid_supp, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (valid_supp, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) valid_supp, "clicked",
                    G_CALLBACK (on_valid_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog10, dialog10, "dialog10");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog10, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dialog10, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (dialog10, label125, "label125");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog10, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (dialog10, valid_supp, "valid_supp");

  return dialog10;
}

GtkWidget*
create_dialog11 (void)
{
  GtkWidget *dialog11;
  GtkWidget *dialog_vbox5;
  GtkWidget *fixed22;
  GtkWidget *label132;
  GtkWidget *dialog_action_area5;
  GtkWidget *valide_ajout_precipitation;

  dialog11 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog11), _("dialog11"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog11), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog11), FALSE);

  dialog_vbox5 = GTK_DIALOG (dialog11)->vbox;
  gtk_widget_show (dialog_vbox5);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), fixed22, TRUE, TRUE, 0);

  label132 = gtk_label_new (_("Ajout valid\303\251"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed22), label132, 32, 40);
  gtk_widget_set_size_request (label132, 168, 32);

  dialog_action_area5 = GTK_DIALOG (dialog11)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  valide_ajout_precipitation = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (valide_ajout_precipitation);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog11), valide_ajout_precipitation, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (valide_ajout_precipitation, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) valide_ajout_precipitation, "clicked",
                    G_CALLBACK (on_valide_ajout_precipitation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog11, dialog11, "dialog11");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog11, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (dialog11, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (dialog11, label132, "label132");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog11, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (dialog11, valide_ajout_precipitation, "valide_ajout_precipitation");

  return dialog11;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed23;
  GtkWidget *label168;
  GtkWidget *label197;
  GtkWidget *label183;
  GtkWidget *label170;
  GtkWidget *label171;
  GtkWidget *label172;
  GtkWidget *label174;
  GtkWidget *label175;
  GtkWidget *label173;
  GtkWidget *label176;
  GtkWidget *label177;
  GtkWidget *label178;
  GtkWidget *label179;
  GtkWidget *label180;
  GtkWidget *label181;
  GtkWidget *label_annee_seche;
  GtkWidget *label_moyenne;
  GtkWidget *label182;
  GtkWidget *label198;
  GtkWidget *label199;
  GtkWidget *label200;
  GtkWidget *label213;
  GtkWidget *label214;
  GtkWidget *label201;
  GtkWidget *label202;
  GtkWidget *label203;
  GtkWidget *label204;
  GtkWidget *label205;
  GtkWidget *label206;
  GtkWidget *label207;
  GtkWidget *label208;
  GtkWidget *label209;
  GtkWidget *label210;
  GtkWidget *label211;
  GtkWidget *label212;
  GtkWidget *label_m12;
  GtkWidget *label_m11;
  GtkWidget *label_m10;
  GtkWidget *label_m9;
  GtkWidget *label_m8;
  GtkWidget *label_m1;
  GtkWidget *label_m2;
  GtkWidget *label_m3;
  GtkWidget *label_m4;
  GtkWidget *label_m5;
  GtkWidget *label_m6;
  GtkWidget *label_m7;
  GtkWidget *label216;
  GtkWidget *label_rapport;
  GtkWidget *label215;
  GtkWidget *label_ref_max;
  GtkWidget *label217;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, -1, 500);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (window1), fixed23);

  label168 = gtk_label_new (_("L'ann\303\251e la plus s\303\250che :"));
  gtk_widget_show (label168);
  gtk_fixed_put (GTK_FIXED (fixed23), label168, 24, 48);
  gtk_widget_set_size_request (label168, 160, 16);

  label197 = gtk_label_new (_("Pr\303\251cipitation (mm/h)"));
  gtk_widget_show (label197);
  gtk_fixed_put (GTK_FIXED (fixed23), label197, 168, 104);
  gtk_widget_set_size_request (label197, 192, 16);

  label183 = gtk_label_new (_("mois"));
  gtk_widget_show (label183);
  gtk_fixed_put (GTK_FIXED (fixed23), label183, 40, 104);
  gtk_widget_set_size_request (label183, 57, 17);

  label170 = gtk_label_new (_("Janvier"));
  gtk_widget_show (label170);
  gtk_fixed_put (GTK_FIXED (fixed23), label170, 32, 128);
  gtk_widget_set_size_request (label170, 72, 16);

  label171 = gtk_label_new (_("F\303\251vrier"));
  gtk_widget_show (label171);
  gtk_fixed_put (GTK_FIXED (fixed23), label171, 32, 152);
  gtk_widget_set_size_request (label171, 72, 16);

  label172 = gtk_label_new (_("Mars"));
  gtk_widget_show (label172);
  gtk_fixed_put (GTK_FIXED (fixed23), label172, 40, 176);
  gtk_widget_set_size_request (label172, 57, 17);

  label174 = gtk_label_new (_("Avril"));
  gtk_widget_show (label174);
  gtk_fixed_put (GTK_FIXED (fixed23), label174, 40, 200);
  gtk_widget_set_size_request (label174, 57, 17);

  label175 = gtk_label_new (_("May"));
  gtk_widget_show (label175);
  gtk_fixed_put (GTK_FIXED (fixed23), label175, 40, 224);
  gtk_widget_set_size_request (label175, 57, 17);

  label173 = gtk_label_new (_("Juin"));
  gtk_widget_show (label173);
  gtk_fixed_put (GTK_FIXED (fixed23), label173, 40, 248);
  gtk_widget_set_size_request (label173, 57, 17);

  label176 = gtk_label_new (_("Juillet"));
  gtk_widget_show (label176);
  gtk_fixed_put (GTK_FIXED (fixed23), label176, 40, 272);
  gtk_widget_set_size_request (label176, 57, 17);

  label177 = gtk_label_new (_("Aout"));
  gtk_widget_show (label177);
  gtk_fixed_put (GTK_FIXED (fixed23), label177, 40, 296);
  gtk_widget_set_size_request (label177, 57, 17);

  label178 = gtk_label_new (_("Septembre"));
  gtk_widget_show (label178);
  gtk_fixed_put (GTK_FIXED (fixed23), label178, 24, 320);
  gtk_widget_set_size_request (label178, 88, 17);

  label179 = gtk_label_new (_("Octobre"));
  gtk_widget_show (label179);
  gtk_fixed_put (GTK_FIXED (fixed23), label179, 24, 344);
  gtk_widget_set_size_request (label179, 80, 17);

  label180 = gtk_label_new (_("Novombre"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed23), label180, 16, 368);
  gtk_widget_set_size_request (label180, 96, 16);

  label181 = gtk_label_new (_("Decembre"));
  gtk_widget_show (label181);
  gtk_fixed_put (GTK_FIXED (fixed23), label181, 16, 392);
  gtk_widget_set_size_request (label181, 104, 16);

  label_annee_seche = gtk_label_new ("");
  gtk_widget_show (label_annee_seche);
  gtk_fixed_put (GTK_FIXED (fixed23), label_annee_seche, 232, 48);
  gtk_widget_set_size_request (label_annee_seche, 57, 17);

  label_moyenne = gtk_label_new ("");
  gtk_widget_show (label_moyenne);
  gtk_fixed_put (GTK_FIXED (fixed23), label_moyenne, 232, 72);
  gtk_widget_set_size_request (label_moyenne, 57, 17);

  label182 = gtk_label_new (_("moyenne :"));
  gtk_widget_show (label182);
  gtk_fixed_put (GTK_FIXED (fixed23), label182, 56, 72);
  gtk_widget_set_size_request (label182, 88, 16);

  label198 = gtk_label_new (_("L'ann\303\251e la moin s\303\250che :"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed23), label198, 384, 48);
  gtk_widget_set_size_request (label198, 176, 16);

  label199 = gtk_label_new (_("moyenne :"));
  gtk_widget_show (label199);
  gtk_fixed_put (GTK_FIXED (fixed23), label199, 432, 72);
  gtk_widget_set_size_request (label199, 97, 16);

  label200 = gtk_label_new (_("Pr\303\251cipitation (mm/h)"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed23), label200, 512, 104);
  gtk_widget_set_size_request (label200, 184, 16);

  label213 = gtk_label_new ("");
  gtk_widget_show (label213);
  gtk_fixed_put (GTK_FIXED (fixed23), label213, 592, 48);
  gtk_widget_set_size_request (label213, 80, 17);

  label214 = gtk_label_new ("");
  gtk_widget_show (label214);
  gtk_fixed_put (GTK_FIXED (fixed23), label214, 600, 72);
  gtk_widget_set_size_request (label214, 64, 17);

  label201 = gtk_label_new ("");
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed23), label201, 584, 128);
  gtk_widget_set_size_request (label201, 57, 17);

  label202 = gtk_label_new ("");
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed23), label202, 584, 152);
  gtk_widget_set_size_request (label202, 57, 17);

  label203 = gtk_label_new ("");
  gtk_widget_show (label203);
  gtk_fixed_put (GTK_FIXED (fixed23), label203, 584, 176);
  gtk_widget_set_size_request (label203, 57, 17);

  label204 = gtk_label_new ("");
  gtk_widget_show (label204);
  gtk_fixed_put (GTK_FIXED (fixed23), label204, 584, 200);
  gtk_widget_set_size_request (label204, 57, 17);

  label205 = gtk_label_new ("");
  gtk_widget_show (label205);
  gtk_fixed_put (GTK_FIXED (fixed23), label205, 584, 224);
  gtk_widget_set_size_request (label205, 57, 17);

  label206 = gtk_label_new ("");
  gtk_widget_show (label206);
  gtk_fixed_put (GTK_FIXED (fixed23), label206, 584, 248);
  gtk_widget_set_size_request (label206, 57, 17);

  label207 = gtk_label_new ("");
  gtk_widget_show (label207);
  gtk_fixed_put (GTK_FIXED (fixed23), label207, 584, 272);
  gtk_widget_set_size_request (label207, 57, 17);

  label208 = gtk_label_new ("");
  gtk_widget_show (label208);
  gtk_fixed_put (GTK_FIXED (fixed23), label208, 584, 296);
  gtk_widget_set_size_request (label208, 57, 17);

  label209 = gtk_label_new ("");
  gtk_widget_show (label209);
  gtk_fixed_put (GTK_FIXED (fixed23), label209, 584, 320);
  gtk_widget_set_size_request (label209, 57, 17);

  label210 = gtk_label_new ("");
  gtk_widget_show (label210);
  gtk_fixed_put (GTK_FIXED (fixed23), label210, 584, 344);
  gtk_widget_set_size_request (label210, 57, 17);

  label211 = gtk_label_new ("");
  gtk_widget_show (label211);
  gtk_fixed_put (GTK_FIXED (fixed23), label211, 584, 368);
  gtk_widget_set_size_request (label211, 57, 17);

  label212 = gtk_label_new ("");
  gtk_widget_show (label212);
  gtk_fixed_put (GTK_FIXED (fixed23), label212, 584, 392);
  gtk_widget_set_size_request (label212, 57, 17);

  label_m12 = gtk_label_new ("");
  gtk_widget_show (label_m12);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m12, 224, 392);
  gtk_widget_set_size_request (label_m12, 57, 17);

  label_m11 = gtk_label_new ("");
  gtk_widget_show (label_m11);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m11, 224, 368);
  gtk_widget_set_size_request (label_m11, 57, 17);

  label_m10 = gtk_label_new ("");
  gtk_widget_show (label_m10);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m10, 224, 344);
  gtk_widget_set_size_request (label_m10, 57, 17);

  label_m9 = gtk_label_new ("");
  gtk_widget_show (label_m9);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m9, 224, 320);
  gtk_widget_set_size_request (label_m9, 57, 17);

  label_m8 = gtk_label_new ("");
  gtk_widget_show (label_m8);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m8, 224, 296);
  gtk_widget_set_size_request (label_m8, 57, 17);

  label_m1 = gtk_label_new ("");
  gtk_widget_show (label_m1);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m1, 224, 128);
  gtk_widget_set_size_request (label_m1, 57, 17);

  label_m2 = gtk_label_new ("");
  gtk_widget_show (label_m2);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m2, 224, 152);
  gtk_widget_set_size_request (label_m2, 56, 16);

  label_m3 = gtk_label_new ("");
  gtk_widget_show (label_m3);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m3, 224, 176);
  gtk_widget_set_size_request (label_m3, 57, 17);

  label_m4 = gtk_label_new ("");
  gtk_widget_show (label_m4);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m4, 224, 200);
  gtk_widget_set_size_request (label_m4, 57, 17);

  label_m5 = gtk_label_new ("");
  gtk_widget_show (label_m5);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m5, 224, 224);
  gtk_widget_set_size_request (label_m5, 57, 17);

  label_m6 = gtk_label_new ("");
  gtk_widget_show (label_m6);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m6, 224, 248);
  gtk_widget_set_size_request (label_m6, 57, 17);

  label_m7 = gtk_label_new ("");
  gtk_widget_show (label_m7);
  gtk_fixed_put (GTK_FIXED (fixed23), label_m7, 224, 272);
  gtk_widget_set_size_request (label_m7, 57, 17);

  label216 = gtk_label_new (_("La plante qui a donn\303\251e plus de recolte"));
  gtk_widget_show (label216);
  gtk_fixed_put (GTK_FIXED (fixed23), label216, 8, 440);
  gtk_widget_set_size_request (label216, 280, 17);

  label_rapport = gtk_label_new ("");
  gtk_widget_show (label_rapport);
  gtk_fixed_put (GTK_FIXED (fixed23), label_rapport, 576, 440);
  gtk_widget_set_size_request (label_rapport, 48, 16);

  label215 = gtk_label_new (_("%"));
  gtk_widget_show (label215);
  gtk_fixed_put (GTK_FIXED (fixed23), label215, 616, 440);
  gtk_widget_set_size_request (label215, 32, 17);

  label_ref_max = gtk_label_new ("");
  gtk_widget_show (label_ref_max);
  gtk_fixed_put (GTK_FIXED (fixed23), label_ref_max, 288, 440);
  gtk_widget_set_size_request (label_ref_max, 88, 17);

  label217 = gtk_label_new (_("Taux de recolte"));
  gtk_widget_show (label217);
  gtk_fixed_put (GTK_FIXED (fixed23), label217, 424, 440);
  gtk_widget_set_size_request (label217, 144, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window1, label168, "label168");
  GLADE_HOOKUP_OBJECT (window1, label197, "label197");
  GLADE_HOOKUP_OBJECT (window1, label183, "label183");
  GLADE_HOOKUP_OBJECT (window1, label170, "label170");
  GLADE_HOOKUP_OBJECT (window1, label171, "label171");
  GLADE_HOOKUP_OBJECT (window1, label172, "label172");
  GLADE_HOOKUP_OBJECT (window1, label174, "label174");
  GLADE_HOOKUP_OBJECT (window1, label175, "label175");
  GLADE_HOOKUP_OBJECT (window1, label173, "label173");
  GLADE_HOOKUP_OBJECT (window1, label176, "label176");
  GLADE_HOOKUP_OBJECT (window1, label177, "label177");
  GLADE_HOOKUP_OBJECT (window1, label178, "label178");
  GLADE_HOOKUP_OBJECT (window1, label179, "label179");
  GLADE_HOOKUP_OBJECT (window1, label180, "label180");
  GLADE_HOOKUP_OBJECT (window1, label181, "label181");
  GLADE_HOOKUP_OBJECT (window1, label_annee_seche, "label_annee_seche");
  GLADE_HOOKUP_OBJECT (window1, label_moyenne, "label_moyenne");
  GLADE_HOOKUP_OBJECT (window1, label182, "label182");
  GLADE_HOOKUP_OBJECT (window1, label198, "label198");
  GLADE_HOOKUP_OBJECT (window1, label199, "label199");
  GLADE_HOOKUP_OBJECT (window1, label200, "label200");
  GLADE_HOOKUP_OBJECT (window1, label213, "label213");
  GLADE_HOOKUP_OBJECT (window1, label214, "label214");
  GLADE_HOOKUP_OBJECT (window1, label201, "label201");
  GLADE_HOOKUP_OBJECT (window1, label202, "label202");
  GLADE_HOOKUP_OBJECT (window1, label203, "label203");
  GLADE_HOOKUP_OBJECT (window1, label204, "label204");
  GLADE_HOOKUP_OBJECT (window1, label205, "label205");
  GLADE_HOOKUP_OBJECT (window1, label206, "label206");
  GLADE_HOOKUP_OBJECT (window1, label207, "label207");
  GLADE_HOOKUP_OBJECT (window1, label208, "label208");
  GLADE_HOOKUP_OBJECT (window1, label209, "label209");
  GLADE_HOOKUP_OBJECT (window1, label210, "label210");
  GLADE_HOOKUP_OBJECT (window1, label211, "label211");
  GLADE_HOOKUP_OBJECT (window1, label212, "label212");
  GLADE_HOOKUP_OBJECT (window1, label_m12, "label_m12");
  GLADE_HOOKUP_OBJECT (window1, label_m11, "label_m11");
  GLADE_HOOKUP_OBJECT (window1, label_m10, "label_m10");
  GLADE_HOOKUP_OBJECT (window1, label_m9, "label_m9");
  GLADE_HOOKUP_OBJECT (window1, label_m8, "label_m8");
  GLADE_HOOKUP_OBJECT (window1, label_m1, "label_m1");
  GLADE_HOOKUP_OBJECT (window1, label_m2, "label_m2");
  GLADE_HOOKUP_OBJECT (window1, label_m3, "label_m3");
  GLADE_HOOKUP_OBJECT (window1, label_m4, "label_m4");
  GLADE_HOOKUP_OBJECT (window1, label_m5, "label_m5");
  GLADE_HOOKUP_OBJECT (window1, label_m6, "label_m6");
  GLADE_HOOKUP_OBJECT (window1, label_m7, "label_m7");
  GLADE_HOOKUP_OBJECT (window1, label216, "label216");
  GLADE_HOOKUP_OBJECT (window1, label_rapport, "label_rapport");
  GLADE_HOOKUP_OBJECT (window1, label215, "label215");
  GLADE_HOOKUP_OBJECT (window1, label_ref_max, "label_ref_max");
  GLADE_HOOKUP_OBJECT (window1, label217, "label217");

  return window1;
}

