/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_troup (void);
GtkWidget* create_dialog_add (void);
GtkWidget* create_dialog_edit (void);
GtkWidget* create_dialog_event (void);
GtkWidget* create_dialog_milk (void);
