/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook6;
  GtkWidget *fixed23;
  GtkWidget *button_affiche_equipements;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label143;
  GtkWidget *button_modifier_equipement;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label84;
  GtkWidget *button_supprimer_equipement;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label85;
  GtkWidget *button_ajouter_equipement;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label83;
  GtkWidget *label80;
  GtkWidget *fixed31;
  GtkWidget *button_ajouter_entretien;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label126;
  GtkWidget *button_supprimer_entretien;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label124;
  GtkWidget *button_modifier_entretien;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label125;
  GtkWidget *button_affiche_entretiens;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label144;
  GtkWidget *label81;
  GtkWidget *fixed30;
  GtkWidget *entry54;
  GtkWidget *entry55;
  GtkWidget *button32;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label119;
  GtkWidget *label118;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *label120;
  GtkWidget *entry56;
  GtkWidget *label121;
  GtkWidget *label82;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("GESTION D'EQUIPEMENTS"));

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_container_add (GTK_CONTAINER (window1), notebook6);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed23);

  button_affiche_equipements = gtk_button_new ();
  gtk_widget_show (button_affiche_equipements);
  gtk_fixed_put (GTK_FIXED (fixed23), button_affiche_equipements, 100, 70);
  gtk_widget_set_size_request (button_affiche_equipements, 300, 60);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button_affiche_equipements), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("  Liste des \303\251quipements"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox30), label143, FALSE, FALSE, 0);

  button_modifier_equipement = gtk_button_new ();
  gtk_widget_show (button_modifier_equipement);
  gtk_fixed_put (GTK_FIXED (fixed23), button_modifier_equipement, 420, 330);
  gtk_widget_set_size_request (button_modifier_equipement, 300, 60);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_modifier_equipement), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox21), label84, FALSE, FALSE, 0);

  button_supprimer_equipement = gtk_button_new ();
  gtk_widget_show (button_supprimer_equipement);
  gtk_fixed_put (GTK_FIXED (fixed23), button_supprimer_equipement, 630, 460);
  gtk_widget_set_size_request (button_supprimer_equipement, 300, 60);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button_supprimer_equipement), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox22), label85, FALSE, FALSE, 0);

  button_ajouter_equipement = gtk_button_new ();
  gtk_widget_show (button_ajouter_equipement);
  gtk_fixed_put (GTK_FIXED (fixed23), button_ajouter_equipement, 230, 200);
  gtk_widget_set_size_request (button_ajouter_equipement, 300, 60);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_ajouter_equipement), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox20), label83, FALSE, FALSE, 0);

  label80 = gtk_label_new (_("Equipements"));
  gtk_widget_show (label80);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label80);

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed31);

  button_ajouter_entretien = gtk_button_new ();
  gtk_widget_show (button_ajouter_entretien);
  gtk_fixed_put (GTK_FIXED (fixed31), button_ajouter_entretien, 230, 200);
  gtk_widget_set_size_request (button_ajouter_entretien, 300, 60);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button_ajouter_entretien), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label126);
  gtk_box_pack_start (GTK_BOX (hbox29), label126, FALSE, FALSE, 0);

  button_supprimer_entretien = gtk_button_new ();
  gtk_widget_show (button_supprimer_entretien);
  gtk_fixed_put (GTK_FIXED (fixed31), button_supprimer_entretien, 630, 460);
  gtk_widget_set_size_request (button_supprimer_entretien, 300, 60);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button_supprimer_entretien), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label124 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label124);
  gtk_box_pack_start (GTK_BOX (hbox27), label124, FALSE, FALSE, 0);

  button_modifier_entretien = gtk_button_new ();
  gtk_widget_show (button_modifier_entretien);
  gtk_fixed_put (GTK_FIXED (fixed31), button_modifier_entretien, 420, 330);
  gtk_widget_set_size_request (button_modifier_entretien, 300, 60);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button_modifier_entretien), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label125 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox28), label125, FALSE, FALSE, 0);

  button_affiche_entretiens = gtk_button_new ();
  gtk_widget_show (button_affiche_entretiens);
  gtk_fixed_put (GTK_FIXED (fixed31), button_affiche_entretiens, 100, 70);
  gtk_widget_set_size_request (button_affiche_entretiens, 300, 60);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button_affiche_entretiens), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label144 = gtk_label_new_with_mnemonic (_("  Liste des entretiens "));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox31), label144, FALSE, FALSE, 0);

  label81 = gtk_label_new (_("Entretiens"));
  gtk_widget_show (label81);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label81);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed30);

  entry54 = gtk_entry_new ();
  gtk_widget_show (entry54);
  gtk_fixed_put (GTK_FIXED (fixed30), entry54, 464, 128);
  gtk_widget_set_size_request (entry54, 384, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry54), 8226);

  entry55 = gtk_entry_new ();
  gtk_widget_show (entry55);
  gtk_fixed_put (GTK_FIXED (fixed30), entry55, 88, 368);
  gtk_widget_set_size_request (entry55, 896, 144);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry55), 8226);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed30), button32, 736, 560);
  gtk_widget_set_size_request (button32, 272, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button32), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("  Envoyer"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox25), label119, FALSE, FALSE, 0);

  label118 = gtk_label_new (_("Commentaires  :  "));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed30), label118, 0, 264);
  gtk_widget_set_size_request (label118, 184, 96);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251claration Normale"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton11, 616, 208);
  gtk_widget_set_size_request (radiobutton11, 192, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251claration urgente"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton10, 224, 208);
  gtk_widget_set_size_request (radiobutton10, 192, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  label120 = gtk_label_new (_("Type de d\303\251claration :"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed30), label120, 88, 128);
  gtk_widget_set_size_request (label120, 240, 56);

  entry56 = gtk_entry_new ();
  gtk_widget_show (entry56);
  gtk_fixed_put (GTK_FIXED (fixed30), entry56, 464, 32);
  gtk_widget_set_size_request (entry56, 384, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry56), 8226);

  label121 = gtk_label_new (_("Le d\303\251clarant :"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed30), label121, 96, 24);
  gtk_widget_set_size_request (label121, 264, 80);

  label82 = gtk_label_new (_("D\303\251clarations"));
  gtk_widget_show (label82);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label82);

  g_signal_connect ((gpointer) button_affiche_equipements, "clicked",
                    G_CALLBACK (on_button_affiche_equipements_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_equipement, "clicked",
                    G_CALLBACK (on_button_modifier_equipement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_equipement, "clicked",
                    G_CALLBACK (on_button_supprimer_equipement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_equipement, "clicked",
                    G_CALLBACK (on_button_ajouter_equipement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_entretien, "clicked",
                    G_CALLBACK (on_button_ajouter_entretien_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_entretien, "clicked",
                    G_CALLBACK (on_button_supprimer_entretien_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_entretien, "clicked",
                    G_CALLBACK (on_button_modifier_entretien_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affiche_entretiens, "clicked",
                    G_CALLBACK (on_button_affiche_entretiens_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (window1, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window1, button_affiche_equipements, "button_affiche_equipements");
  GLADE_HOOKUP_OBJECT (window1, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window1, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window1, image30, "image30");
  GLADE_HOOKUP_OBJECT (window1, label143, "label143");
  GLADE_HOOKUP_OBJECT (window1, button_modifier_equipement, "button_modifier_equipement");
  GLADE_HOOKUP_OBJECT (window1, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, label84, "label84");
  GLADE_HOOKUP_OBJECT (window1, button_supprimer_equipement, "button_supprimer_equipement");
  GLADE_HOOKUP_OBJECT (window1, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window1, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, button_ajouter_equipement, "button_ajouter_equipement");
  GLADE_HOOKUP_OBJECT (window1, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1, image20, "image20");
  GLADE_HOOKUP_OBJECT (window1, label83, "label83");
  GLADE_HOOKUP_OBJECT (window1, label80, "label80");
  GLADE_HOOKUP_OBJECT (window1, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (window1, button_ajouter_entretien, "button_ajouter_entretien");
  GLADE_HOOKUP_OBJECT (window1, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window1, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, label126, "label126");
  GLADE_HOOKUP_OBJECT (window1, button_supprimer_entretien, "button_supprimer_entretien");
  GLADE_HOOKUP_OBJECT (window1, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window1, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window1, image27, "image27");
  GLADE_HOOKUP_OBJECT (window1, label124, "label124");
  GLADE_HOOKUP_OBJECT (window1, button_modifier_entretien, "button_modifier_entretien");
  GLADE_HOOKUP_OBJECT (window1, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window1, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label125, "label125");
  GLADE_HOOKUP_OBJECT (window1, button_affiche_entretiens, "button_affiche_entretiens");
  GLADE_HOOKUP_OBJECT (window1, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window1, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window1, image31, "image31");
  GLADE_HOOKUP_OBJECT (window1, label144, "label144");
  GLADE_HOOKUP_OBJECT (window1, label81, "label81");
  GLADE_HOOKUP_OBJECT (window1, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (window1, entry54, "entry54");
  GLADE_HOOKUP_OBJECT (window1, entry55, "entry55");
  GLADE_HOOKUP_OBJECT (window1, button32, "button32");
  GLADE_HOOKUP_OBJECT (window1, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label119, "label119");
  GLADE_HOOKUP_OBJECT (window1, label118, "label118");
  GLADE_HOOKUP_OBJECT (window1, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (window1, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (window1, label120, "label120");
  GLADE_HOOKUP_OBJECT (window1, entry56, "entry56");
  GLADE_HOOKUP_OBJECT (window1, label121, "label121");
  GLADE_HOOKUP_OBJECT (window1, label82, "label82");

  return window1;
}

GtkWidget*
create_dialog_ajouter_equipement (void)
{
  GtkWidget *dialog_ajouter_equipement;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed24;
  GtkWidget *id;
  GtkWidget *type;
  GtkWidget *marque;
  GtkWidget *prix;
  GtkWidget *association;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label91;
  GtkWidget *label90;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label145;
  GtkWidget *label146;
  GtkWidget *label147;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *ok_ajouter1;

  dialog_ajouter_equipement = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ajouter_equipement), _("Ajout d'un \303\251quipement"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_ajouter_equipement), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_ajouter_equipement), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_ajouter_equipement)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed24, TRUE, TRUE, 0);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed24), id, 376, 40);
  gtk_widget_set_size_request (id, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  type = gtk_entry_new ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed24), type, 376, 120);
  gtk_widget_set_size_request (type, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (type), 8226);

  marque = gtk_entry_new ();
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed24), marque, 376, 208);
  gtk_widget_set_size_request (marque, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (marque), 8226);

  prix = gtk_entry_new ();
  gtk_widget_show (prix);
  gtk_fixed_put (GTK_FIXED (fixed24), prix, 376, 392);
  gtk_widget_set_size_request (prix, 312, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (prix), 8226);

  association = gtk_entry_new ();
  gtk_widget_show (association);
  gtk_fixed_put (GTK_FIXED (fixed24), association, 376, 480);
  gtk_widget_set_size_request (association, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (association), 8226);

  label88 = gtk_label_new (_("Type :"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed24), label88, 64, 120);
  gtk_widget_set_size_request (label88, 296, 40);

  label89 = gtk_label_new (_("Marque d'\303\251quipement :"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed24), label89, 64, 200);
  gtk_widget_set_size_request (label89, 304, 56);

  label91 = gtk_label_new (_("Associ\303\251 \303\240 l'ouvrier : "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed24), label91, 56, 472);
  gtk_widget_set_size_request (label91, 304, 56);

  label90 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed24), label90, 80, 40);
  gtk_widget_set_size_request (label90, 280, 40);

  jour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed24), jour, 304, 304);
  gtk_widget_set_size_request (jour, 72, 32);

  mois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed24), mois, 520, 304);
  gtk_widget_set_size_request (mois, 64, 32);

  annee_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed24), annee, 712, 304);
  gtk_widget_set_size_request (annee, 64, 32);

  label145 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed24), label145, 200, 312);
  gtk_widget_set_size_request (label145, 57, 17);

  label146 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed24), label146, 416, 312);
  gtk_widget_set_size_request (label146, 57, 17);

  label147 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed24), label147, 624, 312);
  gtk_widget_set_size_request (label147, 57, 17);

  label86 = gtk_label_new (_("Date :"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed24), label86, 0, 296);
  gtk_widget_set_size_request (label86, 200, 56);

  label87 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed24), label87, 112, 400);
  gtk_widget_set_size_request (label87, 200, 48);

  dialog_action_area1 = GTK_DIALOG (dialog_ajouter_equipement)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajouter_equipement), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  ok_ajouter1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_ajouter1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajouter_equipement), ok_ajouter1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_ajouter1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_ajouter1, "clicked",
                    G_CALLBACK (on_ok_ajouter1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_equipement, dialog_ajouter_equipement, "dialog_ajouter_equipement");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_equipement, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, id, "id");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, type, "type");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, marque, "marque");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, prix, "prix");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, association, "association");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label88, "label88");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label89, "label89");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label91, "label91");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label90, "label90");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, jour, "jour");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, mois, "mois");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, annee, "annee");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label145, "label145");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label146, "label146");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label147, "label147");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label86, "label86");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, label87, "label87");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_equipement, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_equipement, ok_ajouter1, "ok_ajouter1");

  return dialog_ajouter_equipement;
}

GtkWidget*
create_dialog_modifier_equipement (void)
{
  GtkWidget *dialog_modifier_equipement;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed32;
  GtkWidget *id;
  GtkWidget *type;
  GtkWidget *marque;
  GtkWidget *date;
  GtkWidget *prix;
  GtkWidget *association;
  GtkWidget *label129;
  GtkWidget *label130;
  GtkWidget *label131;
  GtkWidget *label132;
  GtkWidget *label133;
  GtkWidget *label134;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *ok_modifier1;

  dialog_modifier_equipement = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_modifier_equipement), _("Modification d'un \303\251quipement"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_modifier_equipement), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_modifier_equipement), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_modifier_equipement)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed32, TRUE, TRUE, 0);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed32), id, 376, 40);
  gtk_widget_set_size_request (id, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  type = gtk_entry_new ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed32), type, 376, 120);
  gtk_widget_set_size_request (type, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (type), 8226);

  marque = gtk_entry_new ();
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed32), marque, 376, 208);
  gtk_widget_set_size_request (marque, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (marque), 8226);

  date = gtk_entry_new ();
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed32), date, 376, 296);
  gtk_widget_set_size_request (date, 312, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (date), 8226);

  prix = gtk_entry_new ();
  gtk_widget_show (prix);
  gtk_fixed_put (GTK_FIXED (fixed32), prix, 376, 392);
  gtk_widget_set_size_request (prix, 312, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (prix), 8226);

  association = gtk_entry_new ();
  gtk_widget_show (association);
  gtk_fixed_put (GTK_FIXED (fixed32), association, 376, 480);
  gtk_widget_set_size_request (association, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (association), 8226);

  label129 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed32), label129, 80, 40);
  gtk_widget_set_size_request (label129, 280, 40);

  label130 = gtk_label_new (_("Type :"));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed32), label130, 64, 120);
  gtk_widget_set_size_request (label130, 296, 40);

  label131 = gtk_label_new (_("Marque d'\303\251quipement :"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed32), label131, 64, 200);
  gtk_widget_set_size_request (label131, 304, 56);

  label132 = gtk_label_new (_("Date :"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed32), label132, 112, 296);
  gtk_widget_set_size_request (label132, 200, 56);

  label133 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed32), label133, 112, 400);
  gtk_widget_set_size_request (label133, 200, 48);

  label134 = gtk_label_new (_("Associ\303\251 \303\240 l'ouvrier : "));
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed32), label134, 56, 472);
  gtk_widget_set_size_request (label134, 304, 56);

  dialog_action_area2 = GTK_DIALOG (dialog_modifier_equipement)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modifier_equipement), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  ok_modifier1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_modifier1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modifier_equipement), ok_modifier1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_modifier1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_modifier1, "clicked",
                    G_CALLBACK (on_ok_modifier1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_equipement, dialog_modifier_equipement, "dialog_modifier_equipement");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_equipement, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, id, "id");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, type, "type");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, marque, "marque");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, date, "date");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, prix, "prix");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, association, "association");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label129, "label129");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label130, "label130");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label131, "label131");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label132, "label132");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label133, "label133");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, label134, "label134");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_equipement, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog_modifier_equipement, ok_modifier1, "ok_modifier1");

  return dialog_modifier_equipement;
}

GtkWidget*
create_dialog_supprimer_equipement (void)
{
  GtkWidget *dialog_supprimer_equipement;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed26;
  GtkWidget *id;
  GtkWidget *raison;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *ok_supprimer1;

  dialog_supprimer_equipement = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_supprimer_equipement), _("Suppression d'un \303\251quipement"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_supprimer_equipement), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_supprimer_equipement), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_supprimer_equipement)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed26, TRUE, TRUE, 0);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed26), id, 432, 72);
  gtk_widget_set_size_request (id, 368, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  raison = gtk_entry_new ();
  gtk_widget_show (raison);
  gtk_fixed_put (GTK_FIXED (fixed26), raison, 8, 216);
  gtk_widget_set_size_request (raison, 896, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (raison), 8226);

  label98 = gtk_label_new (_("Identifiant d'\303\251quipement \303\240 supprimer :"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed26), label98, 16, 64);
  gtk_widget_set_size_request (label98, 400, 56);

  label99 = gtk_label_new (_("Raison :"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed26), label99, 0, 144);
  gtk_widget_set_size_request (label99, 128, 88);

  dialog_action_area3 = GTK_DIALOG (dialog_supprimer_equipement)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_supprimer_equipement), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  ok_supprimer1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_supprimer1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_supprimer_equipement), ok_supprimer1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_supprimer1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_supprimer1, "clicked",
                    G_CALLBACK (on_ok_supprimer1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_equipement, dialog_supprimer_equipement, "dialog_supprimer_equipement");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_equipement, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, id, "id");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, raison, "raison");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, label98, "label98");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, label99, "label99");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_equipement, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_equipement, ok_supprimer1, "ok_supprimer1");

  return dialog_supprimer_equipement;
}

GtkWidget*
create_dialog_ajouter_entretien (void)
{
  GtkWidget *dialog_ajouter_entretien;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed29;
  GtkWidget *id_eq;
  GtkWidget *date;
  GtkWidget *entreteneur;
  GtkWidget *montant;
  GtkWidget *label111;
  GtkWidget *reference;
  GtkWidget *label115;
  GtkWidget *id_entr;
  GtkWidget *label113;
  GtkWidget *label135;
  GtkWidget *label114;
  GtkWidget *label112;
  GtkWidget *checkbutton_ajout;
  GtkWidget *radiobutton_espece;
  GSList *radiobutton_espece_group = NULL;
  GtkWidget *radiobutton_autre;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton4;
  GtkWidget *ok_ajouter2;

  dialog_ajouter_entretien = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ajouter_entretien), _("Ajout d'un entretien "));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_ajouter_entretien), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_ajouter_entretien), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_ajouter_entretien)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed29, TRUE, TRUE, 0);

  id_eq = gtk_entry_new ();
  gtk_widget_show (id_eq);
  gtk_fixed_put (GTK_FIXED (fixed29), id_eq, 456, 48);
  gtk_widget_set_size_request (id_eq, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_eq), 8226);

  date = gtk_entry_new ();
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed29), date, 456, 208);
  gtk_widget_set_size_request (date, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (date), 8226);

  entreteneur = gtk_entry_new ();
  gtk_widget_show (entreteneur);
  gtk_fixed_put (GTK_FIXED (fixed29), entreteneur, 456, 288);
  gtk_widget_set_size_request (entreteneur, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entreteneur), 8226);

  montant = gtk_entry_new ();
  gtk_widget_show (montant);
  gtk_fixed_put (GTK_FIXED (fixed29), montant, 368, 400);
  gtk_widget_set_size_request (montant, 168, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (montant), 8226);

  label111 = gtk_label_new (_("Identifiant d'\303\251quipement entretenu :"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed29), label111, 88, 56);
  gtk_widget_set_size_request (label111, 304, 56);

  reference = gtk_entry_new ();
  gtk_widget_show (reference);
  gtk_fixed_put (GTK_FIXED (fixed29), reference, 432, 616);
  gtk_widget_set_size_request (reference, 528, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (reference), 8226);

  label115 = gtk_label_new (_("R\303\251f\303\251rence paiement/facture"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed29), label115, 72, 616);
  gtk_widget_set_size_request (label115, 336, 72);

  id_entr = gtk_entry_new ();
  gtk_widget_show (id_entr);
  gtk_fixed_put (GTK_FIXED (fixed29), id_entr, 456, 128);
  gtk_widget_set_size_request (id_entr, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entr), 8226);

  label113 = gtk_label_new (_("Entreteneur :"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed29), label113, 72, 288);
  gtk_widget_set_size_request (label113, 304, 56);

  label135 = gtk_label_new (_("Donner un identifiant \303\240 cet entretien :"));
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed29), label135, 72, 112);
  gtk_widget_set_size_request (label135, 296, 80);

  label114 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed29), label114, 136, 400);
  gtk_widget_set_size_request (label114, 200, 64);

  label112 = gtk_label_new (_("Date de l'entretien :"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed29), label112, 72, 208);
  gtk_widget_set_size_request (label112, 304, 56);

  checkbutton_ajout = gtk_check_button_new_with_mnemonic (_("Pay\303\251"));
  gtk_widget_show (checkbutton_ajout);
  gtk_fixed_put (GTK_FIXED (fixed29), checkbutton_ajout, 640, 416);
  gtk_widget_set_size_request (checkbutton_ajout, 110, 32);

  radiobutton_espece = gtk_radio_button_new_with_mnemonic (NULL, _("Paiement esp\303\250ce"));
  gtk_widget_show (radiobutton_espece);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton_espece, 288, 544);
  gtk_widget_set_size_request (radiobutton_espece, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_espece), radiobutton_espece_group);
  radiobutton_espece_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_espece));

  radiobutton_autre = gtk_radio_button_new_with_mnemonic (NULL, _("Autre"));
  gtk_widget_show (radiobutton_autre);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton_autre, 672, 544);
  gtk_widget_set_size_request (radiobutton_autre, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_autre), radiobutton_espece_group);
  radiobutton_espece_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_autre));

  dialog_action_area4 = GTK_DIALOG (dialog_ajouter_entretien)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajouter_entretien), cancelbutton4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton4, GTK_CAN_DEFAULT);

  ok_ajouter2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_ajouter2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajouter_entretien), ok_ajouter2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_ajouter2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) checkbutton_ajout, "toggled",
                    G_CALLBACK (on_checkbutton_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_espece, "clicked",
                    G_CALLBACK (on_radiobutton_espece_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_autre, "clicked",
                    G_CALLBACK (on_radiobutton_autre_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok_ajouter2, "clicked",
                    G_CALLBACK (on_ok_ajouter2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_entretien, dialog_ajouter_entretien, "dialog_ajouter_entretien");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_entretien, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, id_eq, "id_eq");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, date, "date");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, entreteneur, "entreteneur");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, montant, "montant");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label111, "label111");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, reference, "reference");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label115, "label115");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, id_entr, "id_entr");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label113, "label113");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label135, "label135");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label114, "label114");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, label112, "label112");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, checkbutton_ajout, "checkbutton_ajout");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, radiobutton_espece, "radiobutton_espece");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, radiobutton_autre, "radiobutton_autre");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajouter_entretien, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, cancelbutton4, "cancelbutton4");
  GLADE_HOOKUP_OBJECT (dialog_ajouter_entretien, ok_ajouter2, "ok_ajouter2");

  return dialog_ajouter_entretien;
}

GtkWidget*
create_dialog_modifier_entretien (void)
{
  GtkWidget *dialog_modifier_entretien;
  GtkWidget *dialog_vbox5;
  GtkWidget *fixed33;
  GtkWidget *id_entr;
  GtkWidget *date;
  GtkWidget *entreteneur;
  GtkWidget *montant;
  GtkWidget *label137;
  GtkWidget *reference;
  GtkWidget *label138;
  GtkWidget *label139;
  GtkWidget *id_eq;
  GtkWidget *label140;
  GtkWidget *label136;
  GtkWidget *label141;
  GtkWidget *radiobutton_espece;
  GSList *radiobutton_espece_group = NULL;
  GtkWidget *radiobutton_autre;
  GSList *radiobutton_autre_group = NULL;
  GtkWidget *checkbutton_ajout;
  GtkWidget *dialog_action_area5;
  GtkWidget *cancelbutton5;
  GtkWidget *ok_modifier2;

  dialog_modifier_entretien = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_modifier_entretien), _("Modification d'un entretien "));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_modifier_entretien), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_modifier_entretien), FALSE);

  dialog_vbox5 = GTK_DIALOG (dialog_modifier_entretien)->vbox;
  gtk_widget_show (dialog_vbox5);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), fixed33, TRUE, TRUE, 0);

  id_entr = gtk_entry_new ();
  gtk_widget_show (id_entr);
  gtk_fixed_put (GTK_FIXED (fixed33), id_entr, 456, 48);
  gtk_widget_set_size_request (id_entr, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entr), 8226);

  date = gtk_entry_new ();
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed33), date, 456, 208);
  gtk_widget_set_size_request (date, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (date), 8226);

  entreteneur = gtk_entry_new ();
  gtk_widget_show (entreteneur);
  gtk_fixed_put (GTK_FIXED (fixed33), entreteneur, 456, 288);
  gtk_widget_set_size_request (entreteneur, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entreteneur), 8226);

  montant = gtk_entry_new ();
  gtk_widget_show (montant);
  gtk_fixed_put (GTK_FIXED (fixed33), montant, 368, 400);
  gtk_widget_set_size_request (montant, 168, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (montant), 8226);

  label137 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed33), label137, 144, 400);
  gtk_widget_set_size_request (label137, 200, 64);

  reference = gtk_entry_new ();
  gtk_widget_show (reference);
  gtk_fixed_put (GTK_FIXED (fixed33), reference, 432, 616);
  gtk_widget_set_size_request (reference, 528, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (reference), 8226);

  label138 = gtk_label_new (_("R\303\251f\303\251rence paiement/facture"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed33), label138, 72, 616);
  gtk_widget_set_size_request (label138, 336, 72);

  label139 = gtk_label_new (_("Date de l'entretien :"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed33), label139, 72, 208);
  gtk_widget_set_size_request (label139, 304, 56);

  id_eq = gtk_entry_new ();
  gtk_widget_show (id_eq);
  gtk_fixed_put (GTK_FIXED (fixed33), id_eq, 456, 128);
  gtk_widget_set_size_request (id_eq, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_eq), 8226);

  label140 = gtk_label_new (_("Entreteneur :"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed33), label140, 72, 288);
  gtk_widget_set_size_request (label140, 304, 56);

  label136 = gtk_label_new (_("Identifiant d'entretien :"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed33), label136, 88, 56);
  gtk_widget_set_size_request (label136, 304, 56);

  label141 = gtk_label_new (_("Identifiant de l'\303\251quipement entretenu :"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed33), label141, 72, 112);
  gtk_widget_set_size_request (label141, 296, 80);

  radiobutton_espece = gtk_radio_button_new_with_mnemonic (NULL, _("Paiement esp\303\250ce"));
  gtk_widget_show (radiobutton_espece);
  gtk_fixed_put (GTK_FIXED (fixed33), radiobutton_espece, 288, 544);
  gtk_widget_set_size_request (radiobutton_espece, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_espece), radiobutton_espece_group);
  radiobutton_espece_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_espece));

  radiobutton_autre = gtk_radio_button_new_with_mnemonic (NULL, _("Autre"));
  gtk_widget_show (radiobutton_autre);
  gtk_fixed_put (GTK_FIXED (fixed33), radiobutton_autre, 672, 544);
  gtk_widget_set_size_request (radiobutton_autre, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_autre), radiobutton_autre_group);
  radiobutton_autre_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_autre));

  checkbutton_ajout = gtk_check_button_new_with_mnemonic (_("Pay\303\251"));
  gtk_widget_show (checkbutton_ajout);
  gtk_fixed_put (GTK_FIXED (fixed33), checkbutton_ajout, 640, 416);
  gtk_widget_set_size_request (checkbutton_ajout, 110, 32);

  dialog_action_area5 = GTK_DIALOG (dialog_modifier_entretien)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  cancelbutton5 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton5);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modifier_entretien), cancelbutton5, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton5, GTK_CAN_DEFAULT);

  ok_modifier2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_modifier2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modifier_entretien), ok_modifier2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_modifier2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) radiobutton_espece, "clicked",
                    G_CALLBACK (on_radiobutton_espece_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_autre, "clicked",
                    G_CALLBACK (on_radiobutton_autre_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_ajout, "toggled",
                    G_CALLBACK (on_checkbutton_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) ok_modifier2, "clicked",
                    G_CALLBACK (on_ok_modifier2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_entretien, dialog_modifier_entretien, "dialog_modifier_entretien");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_entretien, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, id_entr, "id_entr");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, date, "date");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, entreteneur, "entreteneur");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, montant, "montant");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label137, "label137");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, reference, "reference");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label138, "label138");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label139, "label139");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, id_eq, "id_eq");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label140, "label140");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label136, "label136");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, label141, "label141");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, radiobutton_espece, "radiobutton_espece");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, radiobutton_autre, "radiobutton_autre");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, checkbutton_ajout, "checkbutton_ajout");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modifier_entretien, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, cancelbutton5, "cancelbutton5");
  GLADE_HOOKUP_OBJECT (dialog_modifier_entretien, ok_modifier2, "ok_modifier2");

  return dialog_modifier_entretien;
}

GtkWidget*
create_dialog_supprimer_entretien (void)
{
  GtkWidget *dialog_supprimer_entretien;
  GtkWidget *dialog_vbox6;
  GtkWidget *fixed34;
  GtkWidget *label142;
  GtkWidget *id_entr;
  GtkWidget *dialog_action_area6;
  GtkWidget *cancelbutton6;
  GtkWidget *ok_supprimer2;

  dialog_supprimer_entretien = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_supprimer_entretien), _("Suppression d'un entretien "));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_supprimer_entretien), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_supprimer_entretien), FALSE);

  dialog_vbox6 = GTK_DIALOG (dialog_supprimer_entretien)->vbox;
  gtk_widget_show (dialog_vbox6);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), fixed34, TRUE, TRUE, 0);

  label142 = gtk_label_new (_("Identifiant de l'entretien \303\240 supprimer : "));
  gtk_widget_show (label142);
  gtk_fixed_put (GTK_FIXED (fixed34), label142, 16, 56);
  gtk_widget_set_size_request (label142, 304, 96);

  id_entr = gtk_entry_new ();
  gtk_widget_show (id_entr);
  gtk_fixed_put (GTK_FIXED (fixed34), id_entr, 360, 80);
  gtk_widget_set_size_request (id_entr, 304, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entr), 8226);

  dialog_action_area6 = GTK_DIALOG (dialog_supprimer_entretien)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  cancelbutton6 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton6);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_supprimer_entretien), cancelbutton6, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton6, GTK_CAN_DEFAULT);

  ok_supprimer2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_supprimer2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_supprimer_entretien), ok_supprimer2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_supprimer2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_supprimer2, "clicked",
                    G_CALLBACK (on_ok_supprimer2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_entretien, dialog_supprimer_entretien, "dialog_supprimer_entretien");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_entretien, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_entretien, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_entretien, label142, "label142");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_entretien, id_entr, "id_entr");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_supprimer_entretien, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_entretien, cancelbutton6, "cancelbutton6");
  GLADE_HOOKUP_OBJECT (dialog_supprimer_entretien, ok_supprimer2, "ok_supprimer2");

  return dialog_supprimer_entretien;
}

GtkWidget*
create_affiche_equipements (void)
{
  GtkWidget *affiche_equipements;
  GtkWidget *scrolledwindow12;
  GtkWidget *treeview1;

  affiche_equipements = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affiche_equipements), _("Liste des \303\251quipements"));

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (affiche_equipements), scrolledwindow12);
  gtk_widget_set_size_request (scrolledwindow12, 1008, 488);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), treeview1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affiche_equipements, affiche_equipements, "affiche_equipements");
  GLADE_HOOKUP_OBJECT (affiche_equipements, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (affiche_equipements, treeview1, "treeview1");

  return affiche_equipements;
}

GtkWidget*
create_affiche_entretiens (void)
{
  GtkWidget *affiche_entretiens;
  GtkWidget *scrolledwindow13;
  GtkWidget *treeview2;

  affiche_entretiens = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affiche_entretiens), _("Liste des entretiens"));

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow13);
  gtk_container_add (GTK_CONTAINER (affiche_entretiens), scrolledwindow13);
  gtk_widget_set_size_request (scrolledwindow13, 1008, 488);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), treeview2);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affiche_entretiens, affiche_entretiens, "affiche_entretiens");
  GLADE_HOOKUP_OBJECT (affiche_entretiens, scrolledwindow13, "scrolledwindow13");
  GLADE_HOOKUP_OBJECT (affiche_entretiens, treeview2, "treeview2");

  return affiche_entretiens;
}

