/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gest_ouvrier (void);
GtkWidget* create_dialog_ajout_ouvrier (void);
GtkWidget* create_dialog_modif_ouvrier (void);
GtkWidget* create_window_gest_emp (void);
GtkWidget* create_dialog_ajout_emp (void);
GtkWidget* create_dialog_modif_emp (void);
GtkWidget* create_window_employee_space (void);
GtkWidget* create_window_gestion_des_clients (void);
GtkWidget* create_dialog_ajouter_client (void);
GtkWidget* create_dialog_modifier_client (void);
GtkWidget* create_dialog_reserv (void);
GtkWidget* create_dialog_mod_res (void);
GtkWidget* create_window_espace_admin (void);
GtkWidget* create_dialog_parametre_admin (void);
GtkWidget* create_window_dashbord_client (void);
GtkWidget* create_dialog_meilleur_ouv (void);
GtkWidget* create_dialog_taux_abs (void);
