/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gest_ouvrier (void);
GtkWidget* create_dialog_ajout_ouvrier (void);
GtkWidget* create_dialog_modif_ouvrier (void);
GtkWidget* create_window_gest_emp (void);
GtkWidget* create_dialog_ajout_emp (void);
GtkWidget* create_dialog_modif_emp (void);
