/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook6;
  GtkWidget *fixed23;
  GtkWidget *button27;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label83;
  GtkWidget *button28;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label84;
  GtkWidget *button29;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label85;
  GtkWidget *scrolledwindow10;
  GtkWidget *treeview9;
  GtkWidget *label80;
  GtkWidget *fixed27;
  GtkWidget *button30;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label100;
  GtkWidget *scrolledwindow11;
  GtkWidget *treeview10;
  GtkWidget *label81;
  GtkWidget *fixed30;
  GtkWidget *entry54;
  GtkWidget *entry55;
  GtkWidget *button32;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label119;
  GtkWidget *label118;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *label120;
  GtkWidget *entry56;
  GtkWidget *label121;
  GtkWidget *label82;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_container_add (GTK_CONTAINER (window1), notebook6);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed23);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed23), button27, 720, 88);
  gtk_widget_set_size_request (button27, 184, 80);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button27), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox20), label83, FALSE, FALSE, 0);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed23), button28, 728, 296);
  gtk_widget_set_size_request (button28, 184, 80);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button28), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox21), label84, FALSE, FALSE, 0);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed23), button29, 728, 496);
  gtk_widget_set_size_request (button29, 184, 80);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button29), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox22), label85, FALSE, FALSE, 0);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow10);
  gtk_fixed_put (GTK_FIXED (fixed23), scrolledwindow10, 0, 0);
  gtk_widget_set_size_request (scrolledwindow10, 600, 688);

  treeview9 = gtk_tree_view_new ();
  gtk_widget_show (treeview9);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), treeview9);

  label80 = gtk_label_new (_("Equipements"));
  gtk_widget_show (label80);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label80);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed27);

  button30 = gtk_button_new ();
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed27), button30, 720, 272);
  gtk_widget_set_size_request (button30, 200, 104);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button30), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox23), label100, FALSE, FALSE, 0);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow11);
  gtk_fixed_put (GTK_FIXED (fixed27), scrolledwindow11, 0, 0);
  gtk_widget_set_size_request (scrolledwindow11, 592, 688);

  treeview10 = gtk_tree_view_new ();
  gtk_widget_show (treeview10);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), treeview10);

  label81 = gtk_label_new (_("Entretiens"));
  gtk_widget_show (label81);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label81);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed30);

  entry54 = gtk_entry_new ();
  gtk_widget_show (entry54);
  gtk_fixed_put (GTK_FIXED (fixed30), entry54, 464, 128);
  gtk_widget_set_size_request (entry54, 384, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry54), 8226);

  entry55 = gtk_entry_new ();
  gtk_widget_show (entry55);
  gtk_fixed_put (GTK_FIXED (fixed30), entry55, 88, 368);
  gtk_widget_set_size_request (entry55, 896, 144);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry55), 8226);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed30), button32, 736, 560);
  gtk_widget_set_size_request (button32, 272, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button32), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("  Envoyer"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox25), label119, FALSE, FALSE, 0);

  label118 = gtk_label_new (_("Commentaires  :  "));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed30), label118, 0, 264);
  gtk_widget_set_size_request (label118, 184, 96);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251claration Normale"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton11, 616, 208);
  gtk_widget_set_size_request (radiobutton11, 192, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251claration urgente"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton10, 224, 208);
  gtk_widget_set_size_request (radiobutton10, 192, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  label120 = gtk_label_new (_("Type de d\303\251claration :"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed30), label120, 88, 128);
  gtk_widget_set_size_request (label120, 240, 56);

  entry56 = gtk_entry_new ();
  gtk_widget_show (entry56);
  gtk_fixed_put (GTK_FIXED (fixed30), entry56, 464, 32);
  gtk_widget_set_size_request (entry56, 384, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry56), 8226);

  label121 = gtk_label_new (_("Le d\303\251clarant :"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed30), label121, 96, 24);
  gtk_widget_set_size_request (label121, 264, 80);

  label82 = gtk_label_new (_("D\303\251clarations"));
  gtk_widget_show (label82);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label82);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (window1, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window1, button27, "button27");
  GLADE_HOOKUP_OBJECT (window1, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1, image20, "image20");
  GLADE_HOOKUP_OBJECT (window1, label83, "label83");
  GLADE_HOOKUP_OBJECT (window1, button28, "button28");
  GLADE_HOOKUP_OBJECT (window1, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, label84, "label84");
  GLADE_HOOKUP_OBJECT (window1, button29, "button29");
  GLADE_HOOKUP_OBJECT (window1, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window1, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (window1, treeview9, "treeview9");
  GLADE_HOOKUP_OBJECT (window1, label80, "label80");
  GLADE_HOOKUP_OBJECT (window1, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (window1, button30, "button30");
  GLADE_HOOKUP_OBJECT (window1, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window1, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label100, "label100");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (window1, treeview10, "treeview10");
  GLADE_HOOKUP_OBJECT (window1, label81, "label81");
  GLADE_HOOKUP_OBJECT (window1, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (window1, entry54, "entry54");
  GLADE_HOOKUP_OBJECT (window1, entry55, "entry55");
  GLADE_HOOKUP_OBJECT (window1, button32, "button32");
  GLADE_HOOKUP_OBJECT (window1, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label119, "label119");
  GLADE_HOOKUP_OBJECT (window1, label118, "label118");
  GLADE_HOOKUP_OBJECT (window1, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (window1, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (window1, label120, "label120");
  GLADE_HOOKUP_OBJECT (window1, entry56, "entry56");
  GLADE_HOOKUP_OBJECT (window1, label121, "label121");
  GLADE_HOOKUP_OBJECT (window1, label82, "label82");

  return window1;
}

GtkWidget*
create_dialog_add (void)
{
  GtkWidget *dialog_add;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed24;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkWidget *entry30;
  GtkWidget *entry31;
  GtkWidget *label88;
  GtkWidget *label90;
  GtkWidget *entry32;
  GtkWidget *label89;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label91;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog_add = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_add), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_add), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_add), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_add)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed24, TRUE, TRUE, 0);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed24), entry27, 456, 40);
  gtk_widget_set_size_request (entry27, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed24), entry28, 456, 136);
  gtk_widget_set_size_request (entry28, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed24), entry29, 456, 232);
  gtk_widget_set_size_request (entry29, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed24), entry30, 456, 328);
  gtk_widget_set_size_request (entry30, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed24), entry31, 456, 424);
  gtk_widget_set_size_request (entry31, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  label88 = gtk_label_new (_("Type :"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed24), label88, 80, 136);
  gtk_widget_set_size_request (label88, 304, 56);

  label90 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed24), label90, 80, 40);
  gtk_widget_set_size_request (label90, 304, 56);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed24), entry32, 456, 520);
  gtk_widget_set_size_request (entry32, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  label89 = gtk_label_new (_("Marque d'\303\251quipement :"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed24), label89, 80, 232);
  gtk_widget_set_size_request (label89, 304, 56);

  label86 = gtk_label_new (_("Date :"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed24), label86, 136, 328);
  gtk_widget_set_size_request (label86, 200, 56);

  label87 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed24), label87, 136, 424);
  gtk_widget_set_size_request (label87, 200, 48);

  label91 = gtk_label_new (_("Associ\303\251 \303\240 l'ouvrier : "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed24), label91, 72, 520);
  gtk_widget_set_size_request (label91, 304, 56);

  dialog_action_area1 = GTK_DIALOG (dialog_add)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_add), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_add), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_add, "dialog_add");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_add, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (dialog_add, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (dialog_add, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (dialog_add, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (dialog_add, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (dialog_add, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (dialog_add, label88, "label88");
  GLADE_HOOKUP_OBJECT (dialog_add, label90, "label90");
  GLADE_HOOKUP_OBJECT (dialog_add, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (dialog_add, label89, "label89");
  GLADE_HOOKUP_OBJECT (dialog_add, label86, "label86");
  GLADE_HOOKUP_OBJECT (dialog_add, label87, "label87");
  GLADE_HOOKUP_OBJECT (dialog_add, label91, "label91");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_add, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_add, okbutton1, "okbutton1");

  return dialog_add;
}

GtkWidget*
create_dialog_modif (void)
{
  GtkWidget *dialog_modif;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed25;
  GtkWidget *entry33;
  GtkWidget *entry34;
  GtkWidget *entry35;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *entry38;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *label97;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  dialog_modif = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_modif), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_modif), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_modif), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_modif)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed25, TRUE, TRUE, 0);

  entry33 = gtk_entry_new ();
  gtk_widget_show (entry33);
  gtk_fixed_put (GTK_FIXED (fixed25), entry33, 456, 40);
  gtk_widget_set_size_request (entry33, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 8226);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed25), entry34, 456, 136);
  gtk_widget_set_size_request (entry34, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  entry35 = gtk_entry_new ();
  gtk_widget_show (entry35);
  gtk_fixed_put (GTK_FIXED (fixed25), entry35, 456, 232);
  gtk_widget_set_size_request (entry35, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry35), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed25), entry36, 456, 328);
  gtk_widget_set_size_request (entry36, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed25), entry37, 456, 424);
  gtk_widget_set_size_request (entry37, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  label92 = gtk_label_new (_("Type :"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed25), label92, 80, 136);
  gtk_widget_set_size_request (label92, 304, 56);

  label93 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed25), label93, 80, 40);
  gtk_widget_set_size_request (label93, 304, 56);

  entry38 = gtk_entry_new ();
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed25), entry38, 456, 520);
  gtk_widget_set_size_request (entry38, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  label94 = gtk_label_new (_("Marque d'\303\251quipement :"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed25), label94, 80, 232);
  gtk_widget_set_size_request (label94, 304, 56);

  label95 = gtk_label_new (_("Date :"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed25), label95, 136, 328);
  gtk_widget_set_size_request (label95, 200, 56);

  label96 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed25), label96, 136, 424);
  gtk_widget_set_size_request (label96, 200, 48);

  label97 = gtk_label_new (_("Associ\303\251 \303\240 l'ouvrier : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed25), label97, 72, 520);
  gtk_widget_set_size_request (label97, 304, 56);

  dialog_action_area2 = GTK_DIALOG (dialog_modif)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modif), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_modif), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modif, dialog_modif, "dialog_modif");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modif, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_modif, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry35, "entry35");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (dialog_modif, label92, "label92");
  GLADE_HOOKUP_OBJECT (dialog_modif, label93, "label93");
  GLADE_HOOKUP_OBJECT (dialog_modif, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (dialog_modif, label94, "label94");
  GLADE_HOOKUP_OBJECT (dialog_modif, label95, "label95");
  GLADE_HOOKUP_OBJECT (dialog_modif, label96, "label96");
  GLADE_HOOKUP_OBJECT (dialog_modif, label97, "label97");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_modif, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_modif, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog_modif, okbutton2, "okbutton2");

  return dialog_modif;
}

GtkWidget*
create_dialog_suppr (void)
{
  GtkWidget *dialog_suppr;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed26;
  GtkWidget *entry39;
  GtkWidget *label98;
  GtkWidget *entry40;
  GtkWidget *label99;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  dialog_suppr = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_suppr), _("dialog3"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_suppr), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_suppr), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_suppr)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed26, TRUE, TRUE, 0);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed26), entry39, 464, 112);
  gtk_widget_set_size_request (entry39, 416, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  label98 = gtk_label_new (_("Identifiant d'\303\251quipement \303\240 supprimer :"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed26), label98, 16, 112);
  gtk_widget_set_size_request (label98, 432, 80);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed26), entry40, 16, 320);
  gtk_widget_set_size_request (entry40, 896, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  label99 = gtk_label_new (_("Raison :"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed26), label99, 0, 248);
  gtk_widget_set_size_request (label99, 128, 88);

  dialog_action_area3 = GTK_DIALOG (dialog_suppr)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_suppr), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_suppr), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_suppr, dialog_suppr, "dialog_suppr");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_suppr, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_suppr, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (dialog_suppr, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (dialog_suppr, label98, "label98");
  GLADE_HOOKUP_OBJECT (dialog_suppr, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (dialog_suppr, label99, "label99");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_suppr, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_suppr, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (dialog_suppr, okbutton3, "okbutton3");

  return dialog_suppr;
}

GtkWidget*
create_dialog_ajout_entretien (void)
{
  GtkWidget *dialog_ajout_entretien;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed29;
  GtkWidget *entry48;
  GtkWidget *entry49;
  GtkWidget *entry50;
  GtkWidget *entry51;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label113;
  GtkWidget *label114;
  GtkWidget *checkbutton2;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *entry52;
  GtkWidget *label115;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton4;
  GtkWidget *okbutton4;

  dialog_ajout_entretien = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ajout_entretien), _("dialog4"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_ajout_entretien), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_ajout_entretien), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_ajout_entretien)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed29, TRUE, TRUE, 0);

  entry48 = gtk_entry_new ();
  gtk_widget_show (entry48);
  gtk_fixed_put (GTK_FIXED (fixed29), entry48, 456, 56);
  gtk_widget_set_size_request (entry48, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry48), 8226);

  entry49 = gtk_entry_new ();
  gtk_widget_show (entry49);
  gtk_fixed_put (GTK_FIXED (fixed29), entry49, 456, 176);
  gtk_widget_set_size_request (entry49, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry49), 8226);

  entry50 = gtk_entry_new ();
  gtk_widget_show (entry50);
  gtk_fixed_put (GTK_FIXED (fixed29), entry50, 456, 296);
  gtk_widget_set_size_request (entry50, 336, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry50), 8226);

  entry51 = gtk_entry_new ();
  gtk_widget_show (entry51);
  gtk_fixed_put (GTK_FIXED (fixed29), entry51, 368, 400);
  gtk_widget_set_size_request (entry51, 168, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry51), 8226);

  label111 = gtk_label_new (_("Identifiant d'\303\251quipement entretenu :"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed29), label111, 88, 56);
  gtk_widget_set_size_request (label111, 304, 56);

  label112 = gtk_label_new (_("Date de l'entretien :"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed29), label112, 88, 176);
  gtk_widget_set_size_request (label112, 304, 56);

  label113 = gtk_label_new (_("Entreteneur :"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed29), label113, 88, 296);
  gtk_widget_set_size_request (label113, 304, 56);

  label114 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed29), label114, 144, 400);
  gtk_widget_set_size_request (label114, 200, 64);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Pay\303\251"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed29), checkbutton2, 640, 416);
  gtk_widget_set_size_request (checkbutton2, 110, 32);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Paiement esp\303\250ce"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton7, 288, 544);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Autre"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton8, 672, 544);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  entry52 = gtk_entry_new ();
  gtk_widget_show (entry52);
  gtk_fixed_put (GTK_FIXED (fixed29), entry52, 448, 616);
  gtk_widget_set_size_request (entry52, 528, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry52), 8226);

  label115 = gtk_label_new (_("R\303\251f\303\251rence paiement/facture"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed29), label115, 72, 616);
  gtk_widget_set_size_request (label115, 336, 72);

  dialog_action_area4 = GTK_DIALOG (dialog_ajout_entretien)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajout_entretien), cancelbutton4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton4, GTK_CAN_DEFAULT);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ajout_entretien), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajout_entretien, dialog_ajout_entretien, "dialog_ajout_entretien");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajout_entretien, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, entry48, "entry48");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, entry49, "entry49");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, entry50, "entry50");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, entry51, "entry51");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, label111, "label111");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, label112, "label112");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, label113, "label113");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, label114, "label114");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, entry52, "entry52");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, label115, "label115");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ajout_entretien, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, cancelbutton4, "cancelbutton4");
  GLADE_HOOKUP_OBJECT (dialog_ajout_entretien, okbutton4, "okbutton4");

  return dialog_ajout_entretien;
}

