/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_des_plantations (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog_modif (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_dialog7 (void);
GtkWidget* create_dialog_modif_plante (void);
