/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dialog_ajout_ouvrier (void);
GtkWidget* create_window_gest_ouvrier (void);
GtkWidget* create_dialog_modif_ouvrier (void);
GtkWidget* create_dialog_modif_employee (void);
GtkWidget* create_dialog_ajout_employee (void);
GtkWidget* create_window_employee_space (void);
GtkWidget* create_window_login (void);
GtkWidget* create_window_gest_employee (void);
GtkWidget* create_window_dashboard (void);
