/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1_gestion_capteurs (void);
GtkWidget* create_Ajouter_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_stat (void);
GtkWidget* create_window_alarmante (void);
GtkWidget* create_max_marque_def (void);
GtkWidget* create_dialog_fiche_capteur (void);
