/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window1_gestion_capteurs;
  GtkWidget *Ajouter_capteur;
  GtkWidget *modifier_capteur;
  GtkWidget *liste_valeur;
  GtkWidget *window_alarmante;
 GtkWidget *stat;
 GtkWidget *max_marque_def;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1_gestion_capteurs = create_window1_gestion_capteurs ();
  gtk_widget_show (window1_gestion_capteurs);
  /*Ajouter_capteur = create_Ajouter_capteur ();
  gtk_widget_show (Ajouter_capteur);
  modifier_capteur = create_modifier_capteur ();
  gtk_widget_show (modifier_capteur);
  liste_valeur = create_liste_valeur ();
  gtk_widget_show (liste_valeur); */
 window_alarmante = create_window_alarmante ();
  gtk_widget_show (window_alarmante);
stat= create_stat();
  gtk_widget_show (stat);
max_marque_def = create_max_marque_def  ();
  gtk_widget_show (max_marque_def );

  gtk_main ();
  return 0; 
}

