/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_employee (void);
GtkWidget* create_window_gestion_des_clients (void);
GtkWidget* create_window_ajouter_client (void);
GtkWidget* create_window_modifier_client (void);
GtkWidget* create_window_ajouter_produit (void);
GtkWidget* create_window_modif_produit (void);
GtkWidget* create_window_aj_facture (void);
GtkWidget* create_window_mod_facture (void);
