/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *fixed1;
  GtkWidget *entry_login_password;
  GtkWidget *entry_login_user;
  GtkWidget *button_login_login;
  GtkWidget *button_login_close;
  GtkWidget *image_login;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_login), 2);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Authentification"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_login), 1024, 745);
  gtk_window_set_type_hint (GTK_WINDOW (window_login), GDK_WINDOW_TYPE_HINT_DESKTOP);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_login), fixed1);

  entry_login_password = gtk_entry_new ();
  gtk_widget_show (entry_login_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_password, 392, 402);
  gtk_widget_set_size_request (entry_login_password, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_password), _("Mot de passe"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_password), 8226);

  entry_login_user = gtk_entry_new ();
  gtk_widget_show (entry_login_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_user, 392, 328);
  gtk_widget_set_size_request (entry_login_user, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_user), _("Identifiant"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_user), 8226);

  button_login_login = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button_login_login);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_login, 392, 472);
  gtk_widget_set_size_request (button_login_login, 240, 56);

  button_login_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (button_login_close);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_close, 456, 544);
  gtk_widget_set_size_request (button_login_close, 96, 29);

  image_login = create_pixmap (window_login, "mahiech finale_Plan de travail 1.png");
  gtk_widget_show (image_login);
  gtk_fixed_put (GTK_FIXED (fixed1), image_login, 0, 0);
  gtk_widget_set_size_request (image_login, 1024, 760);

  g_signal_connect ((gpointer) button_login_close, "clicked",
                    G_CALLBACK (on_button_login_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_password, "entry_login_password");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_user, "entry_login_user");
  GLADE_HOOKUP_OBJECT (window_login, button_login_login, "button_login_login");
  GLADE_HOOKUP_OBJECT (window_login, button_login_close, "button_login_close");
  GLADE_HOOKUP_OBJECT (window_login, image_login, "image_login");

  return window_login;
}

GtkWidget*
create_window_employee (void)
{
  GtkWidget *window_employee;
  GtkWidget *fixed2;
  GtkWidget *button_gestion_ouvriers;
  GtkWidget *button_gestion_equipements;
  GtkWidget *button_gestion_clients;
  GtkWidget *button_calendrier;
  GtkWidget *button_gestion_capteurs;
  GtkWidget *button_gestion_troupeaux;

  window_employee = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_employee), 1);
  gtk_window_set_title (GTK_WINDOW (window_employee), _("Espace employ\303\251s"));
  gtk_window_set_default_size (GTK_WINDOW (window_employee), 1024, 745);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_employee), fixed2);

  button_gestion_ouvriers = gtk_button_new_with_mnemonic (_("Gestion des ouvriers"));
  gtk_widget_show (button_gestion_ouvriers);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_ouvriers, 581, 100);
  gtk_widget_set_size_request (button_gestion_ouvriers, 250, 100);

  button_gestion_equipements = gtk_button_new_with_mnemonic (_("Gestion des \303\251quipements"));
  gtk_widget_show (button_gestion_equipements);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_equipements, 197, 550);
  gtk_widget_set_size_request (button_gestion_equipements, 250, 100);

  button_gestion_clients = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (button_gestion_clients);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_clients, 581, 325);
  gtk_widget_set_size_request (button_gestion_clients, 250, 100);

  button_calendrier = gtk_button_new_with_mnemonic (_("Calendrier "));
  gtk_widget_show (button_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_calendrier, 581, 550);
  gtk_widget_set_size_request (button_calendrier, 250, 100);

  button_gestion_capteurs = gtk_button_new_with_mnemonic (_("Gestion des capteurs"));
  gtk_widget_show (button_gestion_capteurs);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_capteurs, 194, 100);
  gtk_widget_set_size_request (button_gestion_capteurs, 250, 100);

  button_gestion_troupeaux = gtk_button_new_with_mnemonic (_("Gestion des troupeaux"));
  gtk_widget_show (button_gestion_troupeaux);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_troupeaux, 194, 325);
  gtk_widget_set_size_request (button_gestion_troupeaux, 250, 100);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_employee, window_employee, "window_employee");
  GLADE_HOOKUP_OBJECT (window_employee, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_ouvriers, "button_gestion_ouvriers");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_equipements, "button_gestion_equipements");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_clients, "button_gestion_clients");
  GLADE_HOOKUP_OBJECT (window_employee, button_calendrier, "button_calendrier");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_capteurs, "button_gestion_capteurs");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_troupeaux, "button_gestion_troupeaux");

  return window_employee;
}

GtkWidget*
create_window1_gestion_capteurs (void)
{
  GtkWidget *window1_gestion_capteurs;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview4;
  GtkWidget *button6;
  GtkWidget *alignment7;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *button8;
  GtkWidget *alignment5;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *Capteur_temperature;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview5;
  GtkWidget *button10;
  GtkWidget *alignment9;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label13;
  GtkWidget *button9;
  GtkWidget *alignment10;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label14;
  GtkWidget *button11;
  GtkWidget *alignment8;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *fixed13;
  GtkWidget *scrolledwindow7;
  GtkWidget *treeview6;
  GtkWidget *comboboxentry1;
  GtkWidget *button17;
  GtkWidget *alignment16;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label44;
  GtkWidget *label43;

  window1_gestion_capteurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_gestion_capteurs), _("gestion des capteurs"));
  gtk_window_set_default_size (GTK_WINDOW (window1_gestion_capteurs), 1024, 745);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1_gestion_capteurs), notebook1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow5, 168, 16);
  gtk_widget_set_size_request (scrolledwindow5, 888, 440);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview4);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed5), button6, 624, 456);
  gtk_widget_set_size_request (button6, 144, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button6), alignment7);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 768, 456);
  gtk_widget_set_size_request (button7, 144, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed5), button8, 912, 456);
  gtk_widget_set_size_request (button8, 152, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button8), alignment5);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  Capteur_temperature = gtk_label_new (_("capteurs temp\303\251rature"));
  gtk_widget_show (Capteur_temperature);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Capteur_temperature);
  gtk_misc_set_alignment (GTK_MISC (Capteur_temperature), 0.81, 0.5);
  gtk_misc_set_padding (GTK_MISC (Capteur_temperature), 15, 1);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow6, 184, 16);
  gtk_widget_set_size_request (scrolledwindow6, 896, 432);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview5);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 944, 456);
  gtk_widget_set_size_request (button10, 138, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button10), alignment9);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed6), button9, 805, 456);
  gtk_widget_set_size_request (button9, 138, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button9), alignment10);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 666, 456);
  gtk_widget_set_size_request (button11, 138, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button11), alignment8);
  gtk_widget_set_size_request (alignment8, 138, 17);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("capteurs_humidit\303\251"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label11);
  gtk_misc_set_padding (GTK_MISC (label11), 15, 0);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_fixed_put (GTK_FIXED (fixed13), scrolledwindow7, 256, 72);
  gtk_widget_set_size_request (scrolledwindow7, 720, 432);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), treeview6);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry1, 496, 16);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed13), button17, 848, 512);
  gtk_widget_set_size_request (button17, 128, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button17), alignment16);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("enregistrer "));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  label43 = gtk_label_new (_("liste des valeurs "));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label43);
  gtk_misc_set_padding (GTK_MISC (label43), 15, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_gestion_capteurs, window1_gestion_capteurs, "window1_gestion_capteurs");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, Capteur_temperature, "Capteur_temperature");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button17, "button17");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label43, "label43");

  return window1_gestion_capteurs;
}

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed10;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label32;
  GtkWidget *label35;
  GtkWidget *entry10;
  GtkWidget *label36;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  Ajouter = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (Ajouter), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (Ajouter), FALSE);

  dialog_vbox1 = GTK_DIALOG (Ajouter)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed10, TRUE, TRUE, 0);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8, 144, 56);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed10), entry9, 144, 96);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label30 = gtk_label_new (_("marque :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed10), label30, 48, 56);
  gtk_widget_set_size_request (label30, 72, 24);

  label31 = gtk_label_new (_("R\303\251f\303\251rence :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed10), label31, 40, 104);
  gtk_widget_set_size_request (label31, 81, 17);

  spinbutton4_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton4, 176, 144);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton5, 240, 144);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton6, 304, 144);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label32 = gtk_label_new (_("d\303\251but de fonctionnemt :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed10), label32, 8, 144);
  gtk_widget_set_size_request (label32, 168, 24);

  label35 = gtk_label_new (_("Valeur:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed10), label35, 24, 184);
  gtk_widget_set_size_request (label35, 88, 32);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed10), entry10, 144, 184);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label36 = gtk_label_new (_("Ajouter un capteur :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed10), label36, 120, 16);
  gtk_widget_set_size_request (label36, 192, 24);

  dialog_action_area1 = GTK_DIALOG (Ajouter)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (Ajouter), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (Ajouter), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Ajouter, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Ajouter, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Ajouter, label30, "label30");
  GLADE_HOOKUP_OBJECT (Ajouter, label31, "label31");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Ajouter, label32, "label32");
  GLADE_HOOKUP_OBJECT (Ajouter, label35, "label35");
  GLADE_HOOKUP_OBJECT (Ajouter, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Ajouter, label36, "label36");
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (Ajouter, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (Ajouter, okbutton1, "okbutton1");

  return Ajouter;
}

GtkWidget*
create_modifier_ (void)
{
  GtkWidget *modifier_;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed11;
  GtkWidget *entry11;
  GtkWidget *label37;
  GtkWidget *entry12;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  modifier_ = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (modifier_), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (modifier_), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (modifier_), FALSE);

  dialog_vbox2 = GTK_DIALOG (modifier_)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed11, TRUE, TRUE, 0);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed11), entry11, 96, 56);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label37 = gtk_label_new (_("modifier : "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed11), label37, 96, 8);
  gtk_widget_set_size_request (label37, 104, 24);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed11), entry12, 96, 96);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label38 = gtk_label_new (_("r\303\251f\303\251rence : "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed11), label38, 16, 56);
  gtk_widget_set_size_request (label38, 72, 25);

  label39 = gtk_label_new (_("marque :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed11), label39, 16, 96);
  gtk_widget_set_size_request (label39, 64, 25);

  dialog_action_area2 = GTK_DIALOG (modifier_)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (modifier_), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (modifier_), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_, modifier_, "modifier_");
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (modifier_, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (modifier_, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (modifier_, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifier_, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (modifier_, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifier_, label39, "label39");
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (modifier_, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (modifier_, okbutton2, "okbutton2");

  return modifier_;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed12;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  supprimer = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (supprimer), _("dialog3"));
  gtk_window_set_type_hint (GTK_WINDOW (supprimer), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (supprimer), FALSE);

  dialog_vbox3 = GTK_DIALOG (supprimer)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed12, TRUE, TRUE, 0);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed12), entry13, 112, 32);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed12), entry14, 112, 88);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed12), entry15, 112, 136);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label40 = gtk_label_new (_("marque : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed12), label40, 24, 88);
  gtk_widget_set_size_request (label40, 64, 25);

  label41 = gtk_label_new (_("r\303\251f\303\251rence :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed12), label41, 24, 136);
  gtk_widget_set_size_request (label41, 72, 33);

  label42 = gtk_label_new (_("num\303\251ro :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed12), label42, 16, 32);
  gtk_widget_set_size_request (label42, 73, 25);

  dialog_action_area3 = GTK_DIALOG (supprimer)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (supprimer), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (supprimer), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (supprimer, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (supprimer, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (supprimer, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (supprimer, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (supprimer, label40, "label40");
  GLADE_HOOKUP_OBJECT (supprimer, label41, "label41");
  GLADE_HOOKUP_OBJECT (supprimer, label42, "label42");
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (supprimer, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (supprimer, okbutton3, "okbutton3");

  return supprimer;
}

GtkWidget*
create_entrer_une_valeur_ (void)
{
  GtkWidget *entrer_une_valeur_;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed14;
  GtkWidget *entry16;
  GtkWidget *label45;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton4;
  GtkWidget *okbutton4;

  entrer_une_valeur_ = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (entrer_une_valeur_), _("dialog4"));
  gtk_window_set_type_hint (GTK_WINDOW (entrer_une_valeur_), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (entrer_une_valeur_), FALSE);

  dialog_vbox4 = GTK_DIALOG (entrer_une_valeur_)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed14, TRUE, TRUE, 0);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed14), entry16, 72, 56);
  gtk_widget_set_size_request (entry16, 200, 40);
  gtk_entry_set_text (GTK_ENTRY (entry16), _("Entrer une nouvelle valeur "));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  label45 = gtk_label_new (_("valeur : "));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed14), label45, 0, 64);
  gtk_widget_set_size_request (label45, 73, 24);

  dialog_action_area4 = GTK_DIALOG (entrer_une_valeur_)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (entrer_une_valeur_), cancelbutton4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton4, GTK_CAN_DEFAULT);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (entrer_une_valeur_), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (entrer_une_valeur_, entrer_une_valeur_, "entrer_une_valeur_");
  GLADE_HOOKUP_OBJECT_NO_REF (entrer_une_valeur_, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (entrer_une_valeur_, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (entrer_une_valeur_, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (entrer_une_valeur_, label45, "label45");
  GLADE_HOOKUP_OBJECT_NO_REF (entrer_une_valeur_, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (entrer_une_valeur_, cancelbutton4, "cancelbutton4");
  GLADE_HOOKUP_OBJECT (entrer_une_valeur_, okbutton4, "okbutton4");

  return entrer_une_valeur_;
}

