/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_login;
  GtkWidget *window_employee;
  GtkWidget *window1_gestion_capteurs;
  GtkWidget *Ajouter;
  GtkWidget *modifier_;
  GtkWidget *supprimer;
  GtkWidget *entrer_une_valeur_;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_login = create_window_login ();
  gtk_widget_show (window_login);
  window_employee = create_window_employee ();
  gtk_widget_show (window_employee);
  window1_gestion_capteurs = create_window1_gestion_capteurs ();
  gtk_widget_show (window1_gestion_capteurs);
  Ajouter = create_Ajouter ();
  gtk_widget_show (Ajouter);
  modifier_ = create_modifier_ ();
  gtk_widget_show (modifier_);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  entrer_une_valeur_ = create_entrer_une_valeur_ ();
  gtk_widget_show (entrer_une_valeur_);

  gtk_main ();
  return 0;
}

