/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_Gestion_des_plantations (void);
GtkWidget* create_dialog9 (void);
GtkWidget* create_dialog10 (void);
GtkWidget* create_dialog11 (void);
GtkWidget* create_window1 (void);
