/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *fixed1;
  GtkWidget *entry_login_password;
  GtkWidget *entry_login_user;
  GtkWidget *button_login_login;
  GtkWidget *button_login_close;
  GtkWidget *image_login;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_login), 2);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Authentification"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_login), 1024, 745);
  gtk_window_set_type_hint (GTK_WINDOW (window_login), GDK_WINDOW_TYPE_HINT_DESKTOP);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_login), fixed1);

  entry_login_password = gtk_entry_new ();
  gtk_widget_show (entry_login_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_password, 392, 402);
  gtk_widget_set_size_request (entry_login_password, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_password), _("Mot de passe"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_password), 8226);

  entry_login_user = gtk_entry_new ();
  gtk_widget_show (entry_login_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_user, 392, 328);
  gtk_widget_set_size_request (entry_login_user, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_user), _("Identifiant"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_user), 8226);

  button_login_login = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button_login_login);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_login, 392, 472);
  gtk_widget_set_size_request (button_login_login, 240, 56);

  button_login_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (button_login_close);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_close, 456, 544);
  gtk_widget_set_size_request (button_login_close, 96, 29);

  image_login = create_pixmap (window_login, "mahiech finale_Plan de travail 1.png");
  gtk_widget_show (image_login);
  gtk_fixed_put (GTK_FIXED (fixed1), image_login, 0, 0);
  gtk_widget_set_size_request (image_login, 1024, 760);

  g_signal_connect ((gpointer) button_login_close, "clicked",
                    G_CALLBACK (on_button_login_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_password, "entry_login_password");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_user, "entry_login_user");
  GLADE_HOOKUP_OBJECT (window_login, button_login_login, "button_login_login");
  GLADE_HOOKUP_OBJECT (window_login, button_login_close, "button_login_close");
  GLADE_HOOKUP_OBJECT (window_login, image_login, "image_login");

  return window_login;
}

GtkWidget*
create_window_employee (void)
{
  GtkWidget *window_employee;
  GtkWidget *fixed2;
  GtkWidget *button_gestion_ouvriers;
  GtkWidget *button_gestion_equipements;
  GtkWidget *button_gestion_clients;
  GtkWidget *button_calendrier;
  GtkWidget *button_gestion_capteurs;
  GtkWidget *button_gestion_troupeaux;

  window_employee = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_employee), 1);
  gtk_window_set_title (GTK_WINDOW (window_employee), _("Espace employ\303\251s"));
  gtk_window_set_default_size (GTK_WINDOW (window_employee), 1024, 745);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_employee), fixed2);

  button_gestion_ouvriers = gtk_button_new_with_mnemonic (_("Gestion des ouvriers"));
  gtk_widget_show (button_gestion_ouvriers);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_ouvriers, 581, 100);
  gtk_widget_set_size_request (button_gestion_ouvriers, 250, 100);

  button_gestion_equipements = gtk_button_new_with_mnemonic (_("Gestion des \303\251quipements"));
  gtk_widget_show (button_gestion_equipements);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_equipements, 197, 550);
  gtk_widget_set_size_request (button_gestion_equipements, 250, 100);

  button_gestion_clients = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (button_gestion_clients);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_clients, 581, 325);
  gtk_widget_set_size_request (button_gestion_clients, 250, 100);

  button_calendrier = gtk_button_new_with_mnemonic (_("Calendrier "));
  gtk_widget_show (button_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_calendrier, 581, 550);
  gtk_widget_set_size_request (button_calendrier, 250, 100);

  button_gestion_capteurs = gtk_button_new_with_mnemonic (_("Gestion des capteurs"));
  gtk_widget_show (button_gestion_capteurs);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_capteurs, 194, 100);
  gtk_widget_set_size_request (button_gestion_capteurs, 250, 100);

  button_gestion_troupeaux = gtk_button_new_with_mnemonic (_("Gestion des troupeaux"));
  gtk_widget_show (button_gestion_troupeaux);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_troupeaux, 194, 325);
  gtk_widget_set_size_request (button_gestion_troupeaux, 250, 100);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_employee, window_employee, "window_employee");
  GLADE_HOOKUP_OBJECT (window_employee, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_ouvriers, "button_gestion_ouvriers");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_equipements, "button_gestion_equipements");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_clients, "button_gestion_clients");
  GLADE_HOOKUP_OBJECT (window_employee, button_calendrier, "button_calendrier");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_capteurs, "button_gestion_capteurs");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_troupeaux, "button_gestion_troupeaux");

  return window_employee;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");

  return window1;
}

