/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_troup (void)
{
  GtkWidget *window_troup;
  GtkWidget *fixed3;
  GtkWidget *notebook3;
  GtkWidget *fixed13;
  GtkWidget *scrolledwindow12;
  GtkWidget *treeview6;
  GtkWidget *hbuttonbox4;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label97;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label98;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label99;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label103;
  GtkWidget *label47;
  GtkWidget *fixed32;
  GtkWidget *scrolledwindow13;
  GtkWidget *treeview7;
  GtkWidget *hbuttonbox5;
  GtkWidget *button11;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label244;
  GtkWidget *button12;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label245;
  GtkWidget *button13;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label246;
  GtkWidget *button14;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label247;
  GtkWidget *label48;
  GtkWidget *fixed14;
  GtkWidget *textview1;
  GtkWidget *button10;
  GtkWidget *label237;
  GtkWidget *label239;
  GtkWidget *label243;
  GtkWidget *label241;
  GtkWidget *label242;
  GtkWidget *label238;
  GtkWidget *label248;
  GtkWidget *label240;
  GtkWidget *label250;
  GtkWidget *label254;
  GtkWidget *label252;
  GtkWidget *label251;
  GtkWidget *label253;
  GtkWidget *label257;
  GtkWidget *label258;
  GtkWidget *label259;
  GtkWidget *label260;
  GtkWidget *label236;
  GtkWidget *label49;
  GtkWidget *fixed34;
  GtkWidget *entry82;
  GtkWidget *label263;
  GtkWidget *label264;
  GtkWidget *label261;
  GtkWidget *label262;
  GtkWidget *entry83;
  GtkWidget *label256;
  GtkWidget *label265;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton1;
  GtkWidget *button19;
  GtkWidget *alignment13;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label271;
  GtkWidget *label50;
  GtkWidget *alignment8;
  GtkWidget *fixed16;
  GtkWidget *hseparator1;
  GtkWidget *label130;
  GtkWidget *entry34;
  GtkWidget *entry35;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *entry38;
  GtkWidget *entry39;
  GtkWidget *entry40;
  GtkWidget *entry41;
  GtkWidget *entry42;
  GtkWidget *entry43;
  GtkWidget *entry45;
  GtkWidget *entry67;
  GtkWidget *label131;
  GtkWidget *label155;
  GtkWidget *label133;
  GtkWidget *label134;
  GtkWidget *label138;
  GtkWidget *label140;
  GtkWidget *label139;
  GtkWidget *label141;
  GtkWidget *label142;
  GtkWidget *label143;
  GtkWidget *label145;
  GtkWidget *label146;
  GtkWidget *label149;
  GtkWidget *label150;
  GtkWidget *label151;
  GtkWidget *label186;
  GtkWidget *label187;
  GtkWidget *label185;
  GtkWidget *label132;
  GtkWidget *entry72;
  GtkWidget *entry73;
  GtkWidget *entry74;
  GtkWidget *entry75;
  GtkWidget *entry76;
  GtkWidget *entry77;
  GtkWidget *entry78;
  GtkWidget *entry79;
  GtkWidget *entry80;
  GtkWidget *label225;
  GtkWidget *label224;
  GtkWidget *label223;
  GtkWidget *label222;
  GtkWidget *label221;
  GtkWidget *label220;
  GtkWidget *label218;
  GtkWidget *label226;
  GtkWidget *label147;
  GtkWidget *label228;
  GtkWidget *label219;
  GtkWidget *label227;
  GtkWidget *label229;
  GtkWidget *label184;
  GtkWidget *label232;
  GtkWidget *label234;
  GtkWidget *label233;
  GtkWidget *label231;
  GtkWidget *label230;
  GtkWidget *label156;
  GtkWidget *label183;
  GtkWidget *label157;
  GtkWidget *label235;
  GtkWidget *label137;
  GtkWidget *label51;
  GtkWidget *fixed35;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *textview3;
  GtkWidget *label266;
  GtkWidget *label267;
  GtkWidget *label268;
  GtkWidget *button17;
  GtkWidget *button18;
  GtkWidget *label95;
  GtkWidget *fixed33;
  GtkWidget *scrolledwindow14;
  GtkWidget *textview2;
  GtkWidget *label96;

  window_troup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_troup, 1024, 745);
  gtk_window_set_title (GTK_WINDOW (window_troup), _("Gestion des troupeaux"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_troup), fixed3);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook3, 0, 0);
  gtk_widget_set_size_request (notebook3, 1032, 753);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed13);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_fixed_put (GTK_FIXED (fixed13), scrolledwindow12, 96, 80);
  gtk_widget_set_size_request (scrolledwindow12, 840, 432);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), treeview6);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_fixed_put (GTK_FIXED (fixed13), hbuttonbox4, 448, 536);
  gtk_widget_set_size_request (hbuttonbox4, 487, 58);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button1);
  gtk_widget_set_size_request (button1, 74, 38);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox1), label97, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label98 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox2), label98, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox3), label99, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("fiche animal"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox7), label103, FALSE, FALSE, 0);

  label47 = gtk_label_new (_("voeux"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label47);

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed32);

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow13);
  gtk_fixed_put (GTK_FIXED (fixed32), scrolledwindow13, 96, 80);
  gtk_widget_set_size_request (scrolledwindow13, 840, 432);

  treeview7 = gtk_tree_view_new ();
  gtk_widget_show (treeview7);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), treeview7);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_fixed_put (GTK_FIXED (fixed32), hbuttonbox5, 448, 536);
  gtk_widget_set_size_request (hbuttonbox5, 487, 58);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button11);
  gtk_widget_set_size_request (button11, 74, 38);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button11), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label244 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label244);
  gtk_box_pack_start (GTK_BOX (hbox8), label244, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button12), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label245 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label245);
  gtk_box_pack_start (GTK_BOX (hbox9), label245, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label246 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label246);
  gtk_box_pack_start (GTK_BOX (hbox10), label246, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button14), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label247 = gtk_label_new_with_mnemonic (_("fiche animal"));
  gtk_widget_show (label247);
  gtk_box_pack_start (GTK_BOX (hbox11), label247, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("brebis"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label48);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed14);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed14), textview1, 472, 16);
  gtk_widget_set_size_request (textview1, 128, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("<< Fiche Animal >>"), -1);

  button10 = gtk_button_new_with_mnemonic (_("EE006"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed14), button10, 464, 64);
  gtk_widget_set_size_request (button10, 154, 48);

  label237 = gtk_label_new (_("n\303\251 le JJ/MM/AA"));
  gtk_widget_show (label237);
  gtk_fixed_put (GTK_FIXED (fixed14), label237, 480, 120);
  gtk_widget_set_size_request (label237, 124, 17);

  label239 = gtk_label_new (_("xx"));
  gtk_widget_show (label239);
  gtk_fixed_put (GTK_FIXED (fixed14), label239, 536, 152);
  gtk_widget_set_size_request (label239, 57, 17);

  label243 = gtk_label_new (_("Robe:"));
  gtk_widget_show (label243);
  gtk_fixed_put (GTK_FIXED (fixed14), label243, 480, 240);
  gtk_widget_set_size_request (label243, 57, 17);

  label241 = gtk_label_new (_("Poids :"));
  gtk_widget_show (label241);
  gtk_fixed_put (GTK_FIXED (fixed14), label241, 480, 210);
  gtk_widget_set_size_request (label241, 57, 17);

  label242 = gtk_label_new (_("Lot :"));
  gtk_widget_show (label242);
  gtk_fixed_put (GTK_FIXED (fixed14), label242, 484, 270);
  gtk_widget_set_size_request (label242, 57, 17);

  label238 = gtk_label_new (_("Age :"));
  gtk_widget_show (label238);
  gtk_fixed_put (GTK_FIXED (fixed14), label238, 485, 152);
  gtk_widget_set_size_request (label238, 57, 17);

  label248 = gtk_label_new (_("Lait produit:"));
  gtk_widget_show (label248);
  gtk_fixed_put (GTK_FIXED (fixed14), label248, 432, 296);
  gtk_widget_set_size_request (label248, 111, 17);

  label240 = gtk_label_new (_("sexe :"));
  gtk_widget_show (label240);
  gtk_fixed_put (GTK_FIXED (fixed14), label240, 484, 180);
  gtk_widget_set_size_request (label240, 57, 17);

  label250 = gtk_label_new (_("Female"));
  gtk_widget_show (label250);
  gtk_fixed_put (GTK_FIXED (fixed14), label250, 544, 180);
  gtk_widget_set_size_request (label250, 56, 16);

  label254 = gtk_label_new (_("noir"));
  gtk_widget_show (label254);
  gtk_fixed_put (GTK_FIXED (fixed14), label254, 544, 240);
  gtk_widget_set_size_request (label254, 56, 16);

  label252 = gtk_label_new (_("Lactation"));
  gtk_widget_show (label252);
  gtk_fixed_put (GTK_FIXED (fixed14), label252, 544, 270);
  gtk_widget_set_size_request (label252, 70, 16);

  label251 = gtk_label_new (_("1653 L"));
  gtk_widget_show (label251);
  gtk_fixed_put (GTK_FIXED (fixed14), label251, 544, 300);
  gtk_widget_set_size_request (label251, 56, 16);

  label253 = gtk_label_new (_("120 Kg"));
  gtk_widget_show (label253);
  gtk_fixed_put (GTK_FIXED (fixed14), label253, 544, 210);
  gtk_widget_set_size_request (label253, 56, 16);

  label257 = gtk_label_new (_("Gestation : "));
  gtk_widget_show (label257);
  gtk_fixed_put (GTK_FIXED (fixed14), label257, 448, 336);
  gtk_widget_set_size_request (label257, 88, 16);

  label258 = gtk_label_new (_("Sant\303\251:"));
  gtk_widget_show (label258);
  gtk_fixed_put (GTK_FIXED (fixed14), label258, 472, 368);
  gtk_widget_set_size_request (label258, 57, 17);

  label259 = gtk_label_new (_("Negative"));
  gtk_widget_show (label259);
  gtk_fixed_put (GTK_FIXED (fixed14), label259, 544, 336);
  gtk_widget_set_size_request (label259, 63, 17);

  label260 = gtk_label_new (_("seine"));
  gtk_widget_show (label260);
  gtk_fixed_put (GTK_FIXED (fixed14), label260, 544, 368);
  gtk_widget_set_size_request (label260, 57, 17);

  label236 = gtk_label_new (_("mere : EA012"));
  gtk_widget_show (label236);
  gtk_fixed_put (GTK_FIXED (fixed14), label236, 632, 80);
  gtk_widget_set_size_request (label236, 115, 17);

  label49 = gtk_label_new (_("fiche animal"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label49);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed34);

  entry82 = gtk_entry_new ();
  gtk_widget_show (entry82);
  gtk_fixed_put (GTK_FIXED (fixed34), entry82, 336, 56);
  gtk_widget_set_size_request (entry82, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry82), _("Acidoses"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry82), 8226);

  label263 = gtk_label_new (_("Veuillez Introduire la nature du probl\303\251me sanitaire : "));
  gtk_widget_show (label263);
  gtk_fixed_put (GTK_FIXED (fixed34), label263, 208, 96);
  gtk_widget_set_size_request (label263, 428, 17);

  label264 = gtk_label_new (_("Veuillez Introduire la r\303\251ference de l'animal malade :"));
  gtk_widget_show (label264);
  gtk_fixed_put (GTK_FIXED (fixed34), label264, 200, 24);
  gtk_widget_set_size_request (label264, 428, 17);

  label261 = gtk_label_new (_("Mamelle : "));
  gtk_widget_show (label261);
  gtk_fixed_put (GTK_FIXED (fixed34), label261, 336, 136);
  gtk_widget_set_size_request (label261, 90, 17);

  label262 = gtk_label_new (_("Metabolique : "));
  gtk_widget_show (label262);
  gtk_fixed_put (GTK_FIXED (fixed34), label262, 344, 256);
  gtk_widget_set_size_request (label262, 108, 16);

  entry83 = gtk_entry_new ();
  gtk_widget_show (entry83);
  gtk_fixed_put (GTK_FIXED (fixed34), entry83, 344, 408);
  gtk_widget_set_size_request (entry83, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry83), 8226);

  label256 = gtk_label_new (_("reference"));
  gtk_widget_show (label256);
  gtk_fixed_put (GTK_FIXED (fixed34), label256, 240, 56);
  gtk_widget_set_size_request (label256, 79, 26);

  label265 = gtk_label_new (_("autres : "));
  gtk_widget_show (label265);
  gtk_fixed_put (GTK_FIXED (fixed34), label265, 240, 408);
  gtk_widget_set_size_request (label265, 79, 26);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("Mamites sub-cliniques"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton6, 350, 168);
  gtk_widget_set_size_request (checkbutton6, 200, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("Mamites s\303\251v\303\250res"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton5, 350, 208);
  gtk_widget_set_size_request (checkbutton5, 200, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Caillettes"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton4, 350, 288);
  gtk_widget_set_size_request (checkbutton4, 200, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Acidoses cliniques"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton3, 350, 328);
  gtk_widget_set_size_request (checkbutton3, 200, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Ac\303\251ton\303\251mie"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton1, 350, 368);
  gtk_widget_set_size_request (checkbutton1, 200, 24);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed34), button19, 472, 472);
  gtk_widget_set_size_request (button19, 132, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button19), alignment13);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label271 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label271);
  gtk_box_pack_start (GTK_BOX (hbox12), label271, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("sant\303\251"));
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label50);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (notebook3), alignment8);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (alignment8), fixed16);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed16), hseparator1, 0, 24);
  gtk_widget_set_size_request (hseparator1, 1064, 16);

  label130 = gtk_label_new (_("valeur estim\303\251es : "));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed16), label130, 4, 16);
  gtk_widget_set_size_request (label130, 111, 17);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed16), entry34, 84, 160);
  gtk_widget_set_size_request (entry34, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  entry35 = gtk_entry_new ();
  gtk_widget_show (entry35);
  gtk_fixed_put (GTK_FIXED (fixed16), entry35, 84, 130);
  gtk_widget_set_size_request (entry35, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry35), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed16), entry36, 84, 100);
  gtk_widget_set_size_request (entry36, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed16), entry37, 84, 70);
  gtk_widget_set_size_request (entry37, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  entry38 = gtk_entry_new ();
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed16), entry38, 84, 430);
  gtk_widget_set_size_request (entry38, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed16), entry39, 84, 400);
  gtk_widget_set_size_request (entry39, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed16), entry40, 84, 370);
  gtk_widget_set_size_request (entry40, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  entry41 = gtk_entry_new ();
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed16), entry41, 84, 340);
  gtk_widget_set_size_request (entry41, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  entry42 = gtk_entry_new ();
  gtk_widget_show (entry42);
  gtk_fixed_put (GTK_FIXED (fixed16), entry42, 84, 310);
  gtk_widget_set_size_request (entry42, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  entry43 = gtk_entry_new ();
  gtk_widget_show (entry43);
  gtk_fixed_put (GTK_FIXED (fixed16), entry43, 84, 280);
  gtk_widget_set_size_request (entry43, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry43), 8226);

  entry45 = gtk_entry_new ();
  gtk_widget_show (entry45);
  gtk_fixed_put (GTK_FIXED (fixed16), entry45, 84, 250);
  gtk_widget_set_size_request (entry45, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  entry67 = gtk_entry_new ();
  gtk_widget_show (entry67);
  gtk_fixed_put (GTK_FIXED (fixed16), entry67, 320, 70);
  gtk_widget_set_size_request (entry67, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry67), 8226);

  label131 = gtk_label_new (_("UEM"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed16), label131, 20, 100);
  gtk_widget_set_size_request (label131, 57, 17);

  label155 = gtk_label_new (_("%"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed16), label155, 124, 70);
  gtk_widget_set_size_request (label155, 57, 17);

  label133 = gtk_label_new (_("UEL"));
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed16), label133, 20, 130);
  gtk_widget_set_size_request (label133, 57, 17);

  label134 = gtk_label_new (_("UEB"));
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed16), label134, 20, 160);
  gtk_widget_set_size_request (label134, 57, 17);

  label138 = gtk_label_new (_("UEV"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed16), label138, 20, 280);
  gtk_widget_set_size_request (label138, 57, 17);

  label140 = gtk_label_new (_("dMO"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed16), label140, 20, 340);
  gtk_widget_set_size_request (label140, 57, 17);

  label139 = gtk_label_new (_("MO"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed16), label139, 20, 310);
  gtk_widget_set_size_request (label139, 57, 17);

  label141 = gtk_label_new (_("Amidon"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed16), label141, 20, 370);
  gtk_widget_set_size_request (label141, 57, 17);

  label142 = gtk_label_new (_("Sucre"));
  gtk_widget_show (label142);
  gtk_fixed_put (GTK_FIXED (fixed16), label142, 20, 400);
  gtk_widget_set_size_request (label142, 57, 17);

  label143 = gtk_label_new (_("EE/MG"));
  gtk_widget_show (label143);
  gtk_fixed_put (GTK_FIXED (fixed16), label143, 20, 430);
  gtk_widget_set_size_request (label143, 57, 17);

  label145 = gtk_label_new (_("/KgMS"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed16), label145, 120, 250);
  gtk_widget_set_size_request (label145, 57, 17);

  label146 = gtk_label_new (_("/KgMS"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed16), label146, 120, 280);
  gtk_widget_set_size_request (label146, 57, 17);

  label149 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed16), label149, 120, 370);
  gtk_widget_set_size_request (label149, 57, 17);

  label150 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label150);
  gtk_fixed_put (GTK_FIXED (fixed16), label150, 120, 400);
  gtk_widget_set_size_request (label150, 57, 17);

  label151 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label151);
  gtk_fixed_put (GTK_FIXED (fixed16), label151, 120, 430);
  gtk_widget_set_size_request (label151, 57, 17);

  label186 = gtk_label_new (_("ADL"));
  gtk_widget_show (label186);
  gtk_fixed_put (GTK_FIXED (fixed16), label186, 250, 130);
  gtk_widget_set_size_request (label186, 57, 17);

  label187 = gtk_label_new (_("CB"));
  gtk_widget_show (label187);
  gtk_fixed_put (GTK_FIXED (fixed16), label187, 250, 160);
  gtk_widget_set_size_request (label187, 57, 17);

  label185 = gtk_label_new (_("ADF"));
  gtk_widget_show (label185);
  gtk_fixed_put (GTK_FIXED (fixed16), label185, 250, 100);
  gtk_widget_set_size_request (label185, 57, 17);

  label132 = gtk_label_new (_("MS"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed16), label132, 20, 70);
  gtk_widget_set_size_request (label132, 57, 17);

  entry72 = gtk_entry_new ();
  gtk_widget_show (entry72);
  gtk_fixed_put (GTK_FIXED (fixed16), entry72, 320, 400);
  gtk_widget_set_size_request (entry72, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry72), 8226);

  entry73 = gtk_entry_new ();
  gtk_widget_show (entry73);
  gtk_fixed_put (GTK_FIXED (fixed16), entry73, 320, 370);
  gtk_widget_set_size_request (entry73, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry73), 8226);

  entry74 = gtk_entry_new ();
  gtk_widget_show (entry74);
  gtk_fixed_put (GTK_FIXED (fixed16), entry74, 320, 340);
  gtk_widget_set_size_request (entry74, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry74), 8226);

  entry75 = gtk_entry_new ();
  gtk_widget_show (entry75);
  gtk_fixed_put (GTK_FIXED (fixed16), entry75, 320, 310);
  gtk_widget_set_size_request (entry75, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry75), 8226);

  entry76 = gtk_entry_new ();
  gtk_widget_show (entry76);
  gtk_fixed_put (GTK_FIXED (fixed16), entry76, 320, 280);
  gtk_widget_set_size_request (entry76, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry76), 8226);

  entry77 = gtk_entry_new ();
  gtk_widget_show (entry77);
  gtk_fixed_put (GTK_FIXED (fixed16), entry77, 320, 250);
  gtk_widget_set_size_request (entry77, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry77), 8226);

  entry78 = gtk_entry_new ();
  gtk_widget_show (entry78);
  gtk_fixed_put (GTK_FIXED (fixed16), entry78, 320, 100);
  gtk_widget_set_size_request (entry78, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry78), 8226);

  entry79 = gtk_entry_new ();
  gtk_widget_show (entry79);
  gtk_fixed_put (GTK_FIXED (fixed16), entry79, 320, 130);
  gtk_widget_set_size_request (entry79, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry79), 8226);

  entry80 = gtk_entry_new ();
  gtk_widget_show (entry80);
  gtk_fixed_put (GTK_FIXED (fixed16), entry80, 320, 160);
  gtk_widget_set_size_request (entry80, 26, 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry80), 8226);

  label225 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label225);
  gtk_fixed_put (GTK_FIXED (fixed16), label225, 365, 70);
  gtk_widget_set_size_request (label225, 57, 17);

  label224 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label224);
  gtk_fixed_put (GTK_FIXED (fixed16), label224, 365, 100);
  gtk_widget_set_size_request (label224, 57, 17);

  label223 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label223);
  gtk_fixed_put (GTK_FIXED (fixed16), label223, 365, 130);
  gtk_widget_set_size_request (label223, 57, 17);

  label222 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label222);
  gtk_fixed_put (GTK_FIXED (fixed16), label222, 365, 160);
  gtk_widget_set_size_request (label222, 57, 17);

  label221 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label221);
  gtk_fixed_put (GTK_FIXED (fixed16), label221, 365, 250);
  gtk_widget_set_size_request (label221, 57, 17);

  label220 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label220);
  gtk_fixed_put (GTK_FIXED (fixed16), label220, 365, 280);
  gtk_widget_set_size_request (label220, 57, 17);

  label218 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label218);
  gtk_fixed_put (GTK_FIXED (fixed16), label218, 120, 310);
  gtk_widget_set_size_request (label218, 57, 17);

  label226 = gtk_label_new (_("%"));
  gtk_widget_show (label226);
  gtk_fixed_put (GTK_FIXED (fixed16), label226, 120, 340);
  gtk_widget_set_size_request (label226, 57, 17);

  label147 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed16), label147, 365, 310);
  gtk_widget_set_size_request (label147, 57, 17);

  label228 = gtk_label_new (_("g/KgMS"));
  gtk_widget_show (label228);
  gtk_fixed_put (GTK_FIXED (fixed16), label228, 365, 340);
  gtk_widget_set_size_request (label228, 57, 17);

  label219 = gtk_label_new (_("%"));
  gtk_widget_show (label219);
  gtk_fixed_put (GTK_FIXED (fixed16), label219, 365, 370);
  gtk_widget_set_size_request (label219, 57, 17);

  label227 = gtk_label_new (_("%"));
  gtk_widget_show (label227);
  gtk_fixed_put (GTK_FIXED (fixed16), label227, 368, 400);
  gtk_widget_set_size_request (label227, 57, 17);

  label229 = gtk_label_new (_("UFL"));
  gtk_widget_show (label229);
  gtk_fixed_put (GTK_FIXED (fixed16), label229, 20, 250);
  gtk_widget_set_size_request (label229, 57, 17);

  label184 = gtk_label_new (_("NDF"));
  gtk_widget_show (label184);
  gtk_fixed_put (GTK_FIXED (fixed16), label184, 250, 70);
  gtk_widget_set_size_request (label184, 57, 17);

  label232 = gtk_label_new (_("PDIE"));
  gtk_widget_show (label232);
  gtk_fixed_put (GTK_FIXED (fixed16), label232, 250, 280);
  gtk_widget_set_size_request (label232, 68, 17);

  label234 = gtk_label_new (_("PDIA"));
  gtk_widget_show (label234);
  gtk_fixed_put (GTK_FIXED (fixed16), label234, 250, 310);
  gtk_widget_set_size_request (label234, 68, 17);

  label233 = gtk_label_new (_("MAT"));
  gtk_widget_show (label233);
  gtk_fixed_put (GTK_FIXED (fixed16), label233, 250, 340);
  gtk_widget_set_size_request (label233, 68, 17);

  label231 = gtk_label_new (_("LYSDI"));
  gtk_widget_show (label231);
  gtk_fixed_put (GTK_FIXED (fixed16), label231, 250, 370);
  gtk_widget_set_size_request (label231, 68, 17);

  label230 = gtk_label_new (_("METDI"));
  gtk_widget_show (label230);
  gtk_fixed_put (GTK_FIXED (fixed16), label230, 250, 400);
  gtk_widget_set_size_request (label230, 68, 17);

  label156 = gtk_label_new (_("Ingestion"));
  gtk_widget_show (label156);
  gtk_fixed_put (GTK_FIXED (fixed16), label156, 20, 40);
  gtk_widget_set_size_request (label156, 65, 17);

  label183 = gtk_label_new (_("Fibrosit\303\251"));
  gtk_widget_show (label183);
  gtk_fixed_put (GTK_FIXED (fixed16), label183, 250, 40);
  gtk_widget_set_size_request (label183, 62, 17);

  label157 = gtk_label_new (_("Energie"));
  gtk_widget_show (label157);
  gtk_fixed_put (GTK_FIXED (fixed16), label157, 20, 220);
  gtk_widget_set_size_request (label157, 57, 17);

  label235 = gtk_label_new (_("Energie"));
  gtk_widget_show (label235);
  gtk_fixed_put (GTK_FIXED (fixed16), label235, 250, 220);
  gtk_widget_set_size_request (label235, 57, 17);

  label137 = gtk_label_new (_("PDIN"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed16), label137, 250, 250);
  gtk_widget_set_size_request (label137, 68, 17);

  label51 = gtk_label_new (_("alimentation"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 4), label51);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed35);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed35), vseparator1, 576, 32);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed35), vseparator2, 528, 64);
  gtk_widget_set_size_request (vseparator2, 48, 488);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed35), textview3, 584, 72);
  gtk_widget_set_size_request (textview3, 392, 496);

  label266 = gtk_label_new (_("\303\251v\303\250nements r\303\251cents : "));
  gtk_widget_show (label266);
  gtk_fixed_put (GTK_FIXED (fixed35), label266, 568, 40);
  gtk_widget_set_size_request (label266, 192, 17);

  label267 = gtk_label_new (_("Evenements"));
  gtk_widget_show (label267);
  gtk_fixed_put (GTK_FIXED (fixed35), label267, 168, 80);
  gtk_widget_set_size_request (label267, 99, 17);

  label268 = gtk_label_new (_("Production : "));
  gtk_widget_show (label268);
  gtk_fixed_put (GTK_FIXED (fixed35), label268, 176, 272);
  gtk_widget_set_size_request (label268, 92, 17);

  button17 = gtk_button_new_with_mnemonic (_("Ajouter un \303\251v\303\250nement"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed35), button17, 168, 112);
  gtk_widget_set_size_request (button17, 272, 96);

  button18 = gtk_button_new_with_mnemonic (_("laiterie"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed35), button18, 168, 304);
  gtk_widget_set_size_request (button18, 272, 96);

  label95 = gtk_label_new (_("Evenement"));
  gtk_widget_show (label95);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 5), label95);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed33);

  scrolledwindow14 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow14);
  gtk_fixed_put (GTK_FIXED (fixed33), scrolledwindow14, 160, 72);
  gtk_widget_set_size_request (scrolledwindow14, 720, 432);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow14), textview2);
  gtk_widget_set_size_request (textview2, 696, 392);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview2), FALSE);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("Admin : \"Avis pour tous les employ\303\251s \"\nJeudi prochain le  12/11/2020 sera un jour feri\303\251"), -1);

  label96 = gtk_label_new (_("notifications"));
  gtk_widget_show (label96);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 6), label96);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_troup, window_troup, "window_troup");
  GLADE_HOOKUP_OBJECT (window_troup, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_troup, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (window_troup, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window_troup, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (window_troup, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (window_troup, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (window_troup, button1, "button1");
  GLADE_HOOKUP_OBJECT (window_troup, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_troup, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_troup, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_troup, label97, "label97");
  GLADE_HOOKUP_OBJECT (window_troup, button2, "button2");
  GLADE_HOOKUP_OBJECT (window_troup, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_troup, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_troup, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_troup, label98, "label98");
  GLADE_HOOKUP_OBJECT (window_troup, button3, "button3");
  GLADE_HOOKUP_OBJECT (window_troup, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_troup, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_troup, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_troup, label99, "label99");
  GLADE_HOOKUP_OBJECT (window_troup, button7, "button7");
  GLADE_HOOKUP_OBJECT (window_troup, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_troup, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_troup, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_troup, label103, "label103");
  GLADE_HOOKUP_OBJECT (window_troup, label47, "label47");
  GLADE_HOOKUP_OBJECT (window_troup, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (window_troup, scrolledwindow13, "scrolledwindow13");
  GLADE_HOOKUP_OBJECT (window_troup, treeview7, "treeview7");
  GLADE_HOOKUP_OBJECT (window_troup, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (window_troup, button11, "button11");
  GLADE_HOOKUP_OBJECT (window_troup, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_troup, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_troup, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_troup, label244, "label244");
  GLADE_HOOKUP_OBJECT (window_troup, button12, "button12");
  GLADE_HOOKUP_OBJECT (window_troup, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_troup, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_troup, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_troup, label245, "label245");
  GLADE_HOOKUP_OBJECT (window_troup, button13, "button13");
  GLADE_HOOKUP_OBJECT (window_troup, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window_troup, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_troup, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_troup, label246, "label246");
  GLADE_HOOKUP_OBJECT (window_troup, button14, "button14");
  GLADE_HOOKUP_OBJECT (window_troup, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_troup, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window_troup, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_troup, label247, "label247");
  GLADE_HOOKUP_OBJECT (window_troup, label48, "label48");
  GLADE_HOOKUP_OBJECT (window_troup, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window_troup, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window_troup, button10, "button10");
  GLADE_HOOKUP_OBJECT (window_troup, label237, "label237");
  GLADE_HOOKUP_OBJECT (window_troup, label239, "label239");
  GLADE_HOOKUP_OBJECT (window_troup, label243, "label243");
  GLADE_HOOKUP_OBJECT (window_troup, label241, "label241");
  GLADE_HOOKUP_OBJECT (window_troup, label242, "label242");
  GLADE_HOOKUP_OBJECT (window_troup, label238, "label238");
  GLADE_HOOKUP_OBJECT (window_troup, label248, "label248");
  GLADE_HOOKUP_OBJECT (window_troup, label240, "label240");
  GLADE_HOOKUP_OBJECT (window_troup, label250, "label250");
  GLADE_HOOKUP_OBJECT (window_troup, label254, "label254");
  GLADE_HOOKUP_OBJECT (window_troup, label252, "label252");
  GLADE_HOOKUP_OBJECT (window_troup, label251, "label251");
  GLADE_HOOKUP_OBJECT (window_troup, label253, "label253");
  GLADE_HOOKUP_OBJECT (window_troup, label257, "label257");
  GLADE_HOOKUP_OBJECT (window_troup, label258, "label258");
  GLADE_HOOKUP_OBJECT (window_troup, label259, "label259");
  GLADE_HOOKUP_OBJECT (window_troup, label260, "label260");
  GLADE_HOOKUP_OBJECT (window_troup, label236, "label236");
  GLADE_HOOKUP_OBJECT (window_troup, label49, "label49");
  GLADE_HOOKUP_OBJECT (window_troup, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (window_troup, entry82, "entry82");
  GLADE_HOOKUP_OBJECT (window_troup, label263, "label263");
  GLADE_HOOKUP_OBJECT (window_troup, label264, "label264");
  GLADE_HOOKUP_OBJECT (window_troup, label261, "label261");
  GLADE_HOOKUP_OBJECT (window_troup, label262, "label262");
  GLADE_HOOKUP_OBJECT (window_troup, entry83, "entry83");
  GLADE_HOOKUP_OBJECT (window_troup, label256, "label256");
  GLADE_HOOKUP_OBJECT (window_troup, label265, "label265");
  GLADE_HOOKUP_OBJECT (window_troup, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (window_troup, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window_troup, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window_troup, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window_troup, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window_troup, button19, "button19");
  GLADE_HOOKUP_OBJECT (window_troup, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window_troup, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window_troup, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_troup, label271, "label271");
  GLADE_HOOKUP_OBJECT (window_troup, label50, "label50");
  GLADE_HOOKUP_OBJECT (window_troup, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_troup, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (window_troup, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window_troup, label130, "label130");
  GLADE_HOOKUP_OBJECT (window_troup, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (window_troup, entry35, "entry35");
  GLADE_HOOKUP_OBJECT (window_troup, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (window_troup, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (window_troup, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (window_troup, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (window_troup, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (window_troup, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (window_troup, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (window_troup, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (window_troup, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (window_troup, entry67, "entry67");
  GLADE_HOOKUP_OBJECT (window_troup, label131, "label131");
  GLADE_HOOKUP_OBJECT (window_troup, label155, "label155");
  GLADE_HOOKUP_OBJECT (window_troup, label133, "label133");
  GLADE_HOOKUP_OBJECT (window_troup, label134, "label134");
  GLADE_HOOKUP_OBJECT (window_troup, label138, "label138");
  GLADE_HOOKUP_OBJECT (window_troup, label140, "label140");
  GLADE_HOOKUP_OBJECT (window_troup, label139, "label139");
  GLADE_HOOKUP_OBJECT (window_troup, label141, "label141");
  GLADE_HOOKUP_OBJECT (window_troup, label142, "label142");
  GLADE_HOOKUP_OBJECT (window_troup, label143, "label143");
  GLADE_HOOKUP_OBJECT (window_troup, label145, "label145");
  GLADE_HOOKUP_OBJECT (window_troup, label146, "label146");
  GLADE_HOOKUP_OBJECT (window_troup, label149, "label149");
  GLADE_HOOKUP_OBJECT (window_troup, label150, "label150");
  GLADE_HOOKUP_OBJECT (window_troup, label151, "label151");
  GLADE_HOOKUP_OBJECT (window_troup, label186, "label186");
  GLADE_HOOKUP_OBJECT (window_troup, label187, "label187");
  GLADE_HOOKUP_OBJECT (window_troup, label185, "label185");
  GLADE_HOOKUP_OBJECT (window_troup, label132, "label132");
  GLADE_HOOKUP_OBJECT (window_troup, entry72, "entry72");
  GLADE_HOOKUP_OBJECT (window_troup, entry73, "entry73");
  GLADE_HOOKUP_OBJECT (window_troup, entry74, "entry74");
  GLADE_HOOKUP_OBJECT (window_troup, entry75, "entry75");
  GLADE_HOOKUP_OBJECT (window_troup, entry76, "entry76");
  GLADE_HOOKUP_OBJECT (window_troup, entry77, "entry77");
  GLADE_HOOKUP_OBJECT (window_troup, entry78, "entry78");
  GLADE_HOOKUP_OBJECT (window_troup, entry79, "entry79");
  GLADE_HOOKUP_OBJECT (window_troup, entry80, "entry80");
  GLADE_HOOKUP_OBJECT (window_troup, label225, "label225");
  GLADE_HOOKUP_OBJECT (window_troup, label224, "label224");
  GLADE_HOOKUP_OBJECT (window_troup, label223, "label223");
  GLADE_HOOKUP_OBJECT (window_troup, label222, "label222");
  GLADE_HOOKUP_OBJECT (window_troup, label221, "label221");
  GLADE_HOOKUP_OBJECT (window_troup, label220, "label220");
  GLADE_HOOKUP_OBJECT (window_troup, label218, "label218");
  GLADE_HOOKUP_OBJECT (window_troup, label226, "label226");
  GLADE_HOOKUP_OBJECT (window_troup, label147, "label147");
  GLADE_HOOKUP_OBJECT (window_troup, label228, "label228");
  GLADE_HOOKUP_OBJECT (window_troup, label219, "label219");
  GLADE_HOOKUP_OBJECT (window_troup, label227, "label227");
  GLADE_HOOKUP_OBJECT (window_troup, label229, "label229");
  GLADE_HOOKUP_OBJECT (window_troup, label184, "label184");
  GLADE_HOOKUP_OBJECT (window_troup, label232, "label232");
  GLADE_HOOKUP_OBJECT (window_troup, label234, "label234");
  GLADE_HOOKUP_OBJECT (window_troup, label233, "label233");
  GLADE_HOOKUP_OBJECT (window_troup, label231, "label231");
  GLADE_HOOKUP_OBJECT (window_troup, label230, "label230");
  GLADE_HOOKUP_OBJECT (window_troup, label156, "label156");
  GLADE_HOOKUP_OBJECT (window_troup, label183, "label183");
  GLADE_HOOKUP_OBJECT (window_troup, label157, "label157");
  GLADE_HOOKUP_OBJECT (window_troup, label235, "label235");
  GLADE_HOOKUP_OBJECT (window_troup, label137, "label137");
  GLADE_HOOKUP_OBJECT (window_troup, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_troup, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (window_troup, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window_troup, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window_troup, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (window_troup, label266, "label266");
  GLADE_HOOKUP_OBJECT (window_troup, label267, "label267");
  GLADE_HOOKUP_OBJECT (window_troup, label268, "label268");
  GLADE_HOOKUP_OBJECT (window_troup, button17, "button17");
  GLADE_HOOKUP_OBJECT (window_troup, button18, "button18");
  GLADE_HOOKUP_OBJECT (window_troup, label95, "label95");
  GLADE_HOOKUP_OBJECT (window_troup, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (window_troup, scrolledwindow14, "scrolledwindow14");
  GLADE_HOOKUP_OBJECT (window_troup, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (window_troup, label96, "label96");

  return window_troup;
}

GtkWidget*
create_dialog_add (void)
{
  GtkWidget *dialog_add;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed29;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label116;
  GtkWidget *label117;
  GtkWidget *label118;
  GtkWidget *comboboxentry16;
  GtkWidget *comboboxentry17;
  GtkWidget *comboboxentry18;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *entry16;
  GtkWidget *label119;
  GtkWidget *entry17;
  GtkWidget *label120;
  GtkWidget *label121;
  GtkWidget *label122;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog_add = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_add), _("ajouter"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_add), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_add), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_add)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed29, TRUE, TRUE, 0);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed29), entry14, 200, 20);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed29), entry15, 200, 220);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  spinbutton6_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed29), spinbutton6, 200, 180);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label116 = gtk_label_new (_("reference : "));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed29), label116, 20, 20);
  gtk_widget_set_size_request (label116, 77, 17);

  label117 = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed29), label117, 20, 60);
  gtk_widget_set_size_request (label117, 129, 19);

  label118 = gtk_label_new (_("robe :"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed29), label118, 20, 100);
  gtk_widget_set_size_request (label118, 49, 17);

  comboboxentry16 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry16);
  gtk_fixed_put (GTK_FIXED (fixed29), comboboxentry16, 270, 60);
  gtk_widget_set_size_request (comboboxentry16, 61, 24);

  comboboxentry17 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry17);
  gtk_fixed_put (GTK_FIXED (fixed29), comboboxentry17, 200, 60);
  gtk_widget_set_size_request (comboboxentry17, 61, 24);

  comboboxentry18 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry18);
  gtk_fixed_put (GTK_FIXED (fixed29), comboboxentry18, 340, 60);
  gtk_widget_set_size_request (comboboxentry18, 77, 24);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton10, 200, 140);
  gtk_widget_set_size_request (radiobutton10, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("female"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed29), radiobutton11, 340, 140);
  gtk_widget_set_size_request (radiobutton11, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed29), entry16, 200, 100);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  label119 = gtk_label_new (_("genre: "));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed29), label119, 20, 140);
  gtk_widget_set_size_request (label119, 49, 20);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed29), entry17, 200, 260);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  label120 = gtk_label_new (_("poids:"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed29), label120, 20, 180);
  gtk_widget_set_size_request (label120, 43, 25);

  label121 = gtk_label_new (_("reference mere : "));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed29), label121, 20, 220);
  gtk_widget_set_size_request (label121, 113, 17);

  label122 = gtk_label_new (_("Lot:"));
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed29), label122, 20, 260);
  gtk_widget_set_size_request (label122, 57, 17);

  dialog_action_area1 = GTK_DIALOG (dialog_add)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_add), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_add), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_add, "dialog_add");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_add, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (dialog_add, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (dialog_add, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (dialog_add, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (dialog_add, label116, "label116");
  GLADE_HOOKUP_OBJECT (dialog_add, label117, "label117");
  GLADE_HOOKUP_OBJECT (dialog_add, label118, "label118");
  GLADE_HOOKUP_OBJECT (dialog_add, comboboxentry16, "comboboxentry16");
  GLADE_HOOKUP_OBJECT (dialog_add, comboboxentry17, "comboboxentry17");
  GLADE_HOOKUP_OBJECT (dialog_add, comboboxentry18, "comboboxentry18");
  GLADE_HOOKUP_OBJECT (dialog_add, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (dialog_add, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (dialog_add, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (dialog_add, label119, "label119");
  GLADE_HOOKUP_OBJECT (dialog_add, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (dialog_add, label120, "label120");
  GLADE_HOOKUP_OBJECT (dialog_add, label121, "label121");
  GLADE_HOOKUP_OBJECT (dialog_add, label122, "label122");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_add, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_add, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_add, okbutton1, "okbutton1");

  return dialog_add;
}

GtkWidget*
create_dialog_edit (void)
{
  GtkWidget *dialog_edit;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed30;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *label123;
  GtkWidget *label124;
  GtkWidget *label125;
  GtkWidget *comboboxentry19;
  GtkWidget *comboboxentry20;
  GtkWidget *comboboxentry21;
  GtkWidget *radiobutton12;
  GSList *radiobutton12_group = NULL;
  GtkWidget *radiobutton13;
  GSList *radiobutton13_group = NULL;
  GtkWidget *entry20;
  GtkWidget *label126;
  GtkWidget *entry21;
  GtkWidget *label127;
  GtkWidget *label128;
  GtkWidget *label129;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  dialog_edit = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_edit), _("modification"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_edit), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_edit), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_edit)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed30, TRUE, TRUE, 0);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed30), entry18, 200, 20);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed30), entry19, 200, 220);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  spinbutton7_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton7, 200, 180);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  label123 = gtk_label_new (_("reference : "));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed30), label123, 20, 20);
  gtk_widget_set_size_request (label123, 77, 17);

  label124 = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed30), label124, 20, 60);
  gtk_widget_set_size_request (label124, 129, 19);

  label125 = gtk_label_new (_("robe :"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed30), label125, 20, 100);
  gtk_widget_set_size_request (label125, 49, 17);

  comboboxentry19 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry19);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry19, 270, 60);
  gtk_widget_set_size_request (comboboxentry19, 61, 24);

  comboboxentry20 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry20);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry20, 200, 60);
  gtk_widget_set_size_request (comboboxentry20, 61, 24);

  comboboxentry21 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry21);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry21, 340, 60);
  gtk_widget_set_size_request (comboboxentry21, 77, 24);

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton12, 200, 140);
  gtk_widget_set_size_request (radiobutton12, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton12_group);
  radiobutton12_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  radiobutton13 = gtk_radio_button_new_with_mnemonic (NULL, _("female"));
  gtk_widget_show (radiobutton13);
  gtk_fixed_put (GTK_FIXED (fixed30), radiobutton13, 340, 140);
  gtk_widget_set_size_request (radiobutton13, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton13_group);
  radiobutton13_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed30), entry20, 200, 100);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label126 = gtk_label_new (_("genre: "));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed30), label126, 20, 140);
  gtk_widget_set_size_request (label126, 49, 20);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed30), entry21, 200, 260);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  label127 = gtk_label_new (_("poids:"));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed30), label127, 20, 180);
  gtk_widget_set_size_request (label127, 43, 25);

  label128 = gtk_label_new (_("reference mere : "));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed30), label128, 20, 220);
  gtk_widget_set_size_request (label128, 113, 17);

  label129 = gtk_label_new (_("Lot:"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed30), label129, 20, 260);
  gtk_widget_set_size_request (label129, 57, 17);

  dialog_action_area2 = GTK_DIALOG (dialog_edit)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_edit), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_edit), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_edit, dialog_edit, "dialog_edit");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_edit, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_edit, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (dialog_edit, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (dialog_edit, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (dialog_edit, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (dialog_edit, label123, "label123");
  GLADE_HOOKUP_OBJECT (dialog_edit, label124, "label124");
  GLADE_HOOKUP_OBJECT (dialog_edit, label125, "label125");
  GLADE_HOOKUP_OBJECT (dialog_edit, comboboxentry19, "comboboxentry19");
  GLADE_HOOKUP_OBJECT (dialog_edit, comboboxentry20, "comboboxentry20");
  GLADE_HOOKUP_OBJECT (dialog_edit, comboboxentry21, "comboboxentry21");
  GLADE_HOOKUP_OBJECT (dialog_edit, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (dialog_edit, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (dialog_edit, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (dialog_edit, label126, "label126");
  GLADE_HOOKUP_OBJECT (dialog_edit, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (dialog_edit, label127, "label127");
  GLADE_HOOKUP_OBJECT (dialog_edit, label128, "label128");
  GLADE_HOOKUP_OBJECT (dialog_edit, label129, "label129");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_edit, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_edit, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog_edit, okbutton2, "okbutton2");

  return dialog_edit;
}

GtkWidget*
create_dialog_event (void)
{
  GtkWidget *dialog_event;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed31;
  GtkWidget *entry81;
  GtkWidget *label255;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GtkWidget *radiobutton16;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  dialog_event = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_event), _("evenement"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_event), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_event), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_event)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed31, TRUE, TRUE, 0);

  entry81 = gtk_entry_new ();
  gtk_widget_show (entry81);
  gtk_fixed_put (GTK_FIXED (fixed31), entry81, 136, 72);
  gtk_widget_set_size_request (entry81, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry81), 8226);

  label255 = gtk_label_new (_("reference"));
  gtk_widget_show (label255);
  gtk_fixed_put (GTK_FIXED (fixed31), label255, 48, 72);
  gtk_widget_set_size_request (label255, 79, 26);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("mort"));
  gtk_widget_show (radiobutton14);
  gtk_fixed_put (GTK_FIXED (fixed31), radiobutton14, 136, 112);
  gtk_widget_set_size_request (radiobutton14, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new_with_mnemonic (NULL, _("Gestation"));
  gtk_widget_show (radiobutton15);
  gtk_fixed_put (GTK_FIXED (fixed31), radiobutton15, 136, 152);
  gtk_widget_set_size_request (radiobutton15, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  radiobutton16 = gtk_radio_button_new_with_mnemonic (NULL, _("malade"));
  gtk_widget_show (radiobutton16);
  gtk_fixed_put (GTK_FIXED (fixed31), radiobutton16, 136, 192);
  gtk_widget_set_size_request (radiobutton16, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton16), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton16));

  dialog_action_area3 = GTK_DIALOG (dialog_event)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_event), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_event), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_event, dialog_event, "dialog_event");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_event, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_event, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (dialog_event, entry81, "entry81");
  GLADE_HOOKUP_OBJECT (dialog_event, label255, "label255");
  GLADE_HOOKUP_OBJECT (dialog_event, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (dialog_event, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (dialog_event, radiobutton16, "radiobutton16");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_event, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_event, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (dialog_event, okbutton3, "okbutton3");

  return dialog_event;
}

GtkWidget*
create_dialog_milk (void)
{
  GtkWidget *dialog_milk;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed36;
  GtkWidget *entry84;
  GtkWidget *entry85;
  GtkWidget *label270;
  GtkWidget *label269;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton4;
  GtkWidget *okbutton4;

  dialog_milk = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_milk), _("Laiterie"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_milk), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_milk), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_milk)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed36 = gtk_fixed_new ();
  gtk_widget_show (fixed36);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed36, TRUE, TRUE, 0);

  entry84 = gtk_entry_new ();
  gtk_widget_show (entry84);
  gtk_fixed_put (GTK_FIXED (fixed36), entry84, 72, 88);
  gtk_widget_set_size_request (entry84, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry84), 8226);

  entry85 = gtk_entry_new ();
  gtk_widget_show (entry85);
  gtk_fixed_put (GTK_FIXED (fixed36), entry85, 72, 144);
  gtk_widget_set_size_request (entry85, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry85), 8226);

  label270 = gtk_label_new (_("Lait produit en Litre"));
  gtk_widget_show (label270);
  gtk_fixed_put (GTK_FIXED (fixed36), label270, 80, 120);
  gtk_widget_set_size_request (label270, 147, 17);

  label269 = gtk_label_new (_("reference de l'animal "));
  gtk_widget_show (label269);
  gtk_fixed_put (GTK_FIXED (fixed36), label269, 56, 56);
  gtk_widget_set_size_request (label269, 183, 26);

  dialog_action_area4 = GTK_DIALOG (dialog_milk)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_milk), cancelbutton4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton4, GTK_CAN_DEFAULT);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_milk), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_milk, dialog_milk, "dialog_milk");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_milk, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_milk, fixed36, "fixed36");
  GLADE_HOOKUP_OBJECT (dialog_milk, entry84, "entry84");
  GLADE_HOOKUP_OBJECT (dialog_milk, entry85, "entry85");
  GLADE_HOOKUP_OBJECT (dialog_milk, label270, "label270");
  GLADE_HOOKUP_OBJECT (dialog_milk, label269, "label269");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_milk, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_milk, cancelbutton4, "cancelbutton4");
  GLADE_HOOKUP_OBJECT (dialog_milk, okbutton4, "okbutton4");

  return dialog_milk;
}

