/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dialog_add_troup (void);
GtkWidget* create_dialog_edit_troup (void);
GtkWidget* create_dialog_event (void);
GtkWidget* create_dialog_milk (void);
GtkWidget* create_dialog_ajout_ouvrier (void);
GtkWidget* create_window_gest_ouvrier (void);
GtkWidget* create_dialog_modif_ouvrier (void);
GtkWidget* create_dialog_modif_employee (void);
GtkWidget* create_dialog_ajout_employee (void);
GtkWidget* create_window_employee_space (void);
GtkWidget* create_dialog_ajouter_client (void);
GtkWidget* create_window_gestion_des_clients (void);
GtkWidget* create_window_troup (void);
GtkWidget* create_dialog_modifier_client (void);
GtkWidget* create_dialog_ajouter_produit (void);
GtkWidget* create_dialog_modifier_produit (void);
GtkWidget* create_dialog_ajouter_facture (void);
GtkWidget* create_dialog_modif_facture (void);
GtkWidget* create_window_login (void);
GtkWidget* create_dialog_commentaire (void);
GtkWidget* create_dialog_add_plant (void);
GtkWidget* create_dialog_delete_plant (void);
GtkWidget* create_window_gestion_capteurs (void);
GtkWidget* create_dialog_capteur_add (void);
GtkWidget* create_dialog_capteur_edit (void);
GtkWidget* create_dialog_capteur_delete (void);
GtkWidget* create_dialog_capteur_add_value (void);
GtkWidget* create_window_gestion_equipment (void);
GtkWidget* create_dialog_add_equipment (void);
GtkWidget* create_dialog_edit_equipment (void);
GtkWidget* create_dialog_delete_equipment (void);
GtkWidget* create_dialog_entretien (void);
GtkWidget* create_window_gest_employee (void);
GtkWidget* create_window_gestion_achat (void);
GtkWidget* create_window_gest_plantations (void);
GtkWidget* create_dialog_edit_plant (void);
