/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_employee_space (void);
GtkWidget* create_dialog_ajouter_client (void);
GtkWidget* create_window_gestion_des_clients (void);
GtkWidget* create_dialog_modifier_client (void);
GtkWidget* create_dialog_ajouter_produit (void);
GtkWidget* create_dialog_modifier_produit (void);
GtkWidget* create_dialog_ajouter_facture (void);
GtkWidget* create_dialog_modif_facture (void);
GtkWidget* create_window_gestion_achat (void);
GtkWidget* create_window_dashboard (void);
