/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed1;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_username;
  GtkWidget *entry_password;
  GtkWidget *entry_role;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label_nom;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton_1;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog1, 450, 400);
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog1), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed1, TRUE, TRUE, 0);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom, 168, 56);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom, 168, 104);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_username = gtk_entry_new ();
  gtk_widget_show (entry_username);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_username, 168, 152);
  gtk_widget_set_size_request (entry_username, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_username), 8226);

  entry_password = gtk_entry_new ();
  gtk_widget_show (entry_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_password, 168, 200);
  gtk_widget_set_size_request (entry_password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_password), 8226);

  entry_role = gtk_entry_new ();
  gtk_widget_show (entry_role);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_role, 168, 248);
  gtk_widget_set_size_request (entry_role, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_role), 8226);

  label2 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 64, 112);
  gtk_widget_set_size_request (label2, 72, 16);

  label3 = gtk_label_new (_("Username :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 56, 160);
  gtk_widget_set_size_request (label3, 80, 16);

  label_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_nom, 88, 64);
  gtk_widget_set_size_request (label_nom, 41, 17);

  label4 = gtk_label_new (_("Password :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 56, 208);
  gtk_widget_set_size_request (label4, 80, 16);

  label5 = gtk_label_new (_("Role :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 96, 256);
  gtk_widget_set_size_request (label5, 41, 17);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton_1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton_1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton_1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton_1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton_1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (dialog1, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (dialog1, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (dialog1, entry_username, "entry_username");
  GLADE_HOOKUP_OBJECT (dialog1, entry_password, "entry_password");
  GLADE_HOOKUP_OBJECT (dialog1, entry_role, "entry_role");
  GLADE_HOOKUP_OBJECT (dialog1, label2, "label2");
  GLADE_HOOKUP_OBJECT (dialog1, label3, "label3");
  GLADE_HOOKUP_OBJECT (dialog1, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (dialog1, label4, "label4");
  GLADE_HOOKUP_OBJECT (dialog1, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton_1, "okbutton_1");

  return dialog1;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed3;
  GtkWidget *label10;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window1), fixed3);

  label10 = gtk_label_new (_("Welcome to espace admin : "));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 40, 40);
  gtk_widget_set_size_request (label10, 232, 88);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");

  return window1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed2;
  GtkWidget *entry_id;
  GtkWidget *entry_pw;
  GtkWidget *label6;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *dialog_action_area2;
  GtkWidget *TEST;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog2, 350, 350);
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed2, TRUE, TRUE, 0);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id, 112, 40);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_pw = gtk_entry_new ();
  gtk_widget_show (entry_pw);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_pw, 112, 96);
  gtk_widget_set_size_request (entry_pw, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pw), 8226);

  label6 = gtk_label_new (_("Username :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 16, 48);
  gtk_widget_set_size_request (label6, 80, 16);

  label9 = gtk_label_new (_("Password :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 16, 104);
  gtk_widget_set_size_request (label9, 80, 16);

  label11 = gtk_label_new ("");
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 80, 152);
  gtk_widget_set_size_request (label11, 208, 97);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  TEST = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (TEST);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), TEST, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (TEST, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) TEST, "clicked",
                    G_CALLBACK (on_TEST_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (dialog2, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (dialog2, entry_pw, "entry_pw");
  GLADE_HOOKUP_OBJECT (dialog2, label6, "label6");
  GLADE_HOOKUP_OBJECT (dialog2, label9, "label9");
  GLADE_HOOKUP_OBJECT (dialog2, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, TEST, "TEST");

  return dialog2;
}

