/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *fixed1;
  GtkWidget *entry_login_password;
  GtkWidget *entry_login_user;
  GtkWidget *button_login_login;
  GtkWidget *button_login_close;
  GtkWidget *image_login;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_login), 2);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Authentification"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_login), 1024, 745);
  gtk_window_set_type_hint (GTK_WINDOW (window_login), GDK_WINDOW_TYPE_HINT_DESKTOP);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_login), fixed1);

  entry_login_password = gtk_entry_new ();
  gtk_widget_show (entry_login_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_password, 392, 402);
  gtk_widget_set_size_request (entry_login_password, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_password), _("Mot de passe"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_password), 8226);

  entry_login_user = gtk_entry_new ();
  gtk_widget_show (entry_login_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_user, 392, 328);
  gtk_widget_set_size_request (entry_login_user, 272, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_login_user), _("Identifiant"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_user), 8226);

  button_login_login = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button_login_login);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_login, 392, 472);
  gtk_widget_set_size_request (button_login_login, 240, 56);

  button_login_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (button_login_close);
  gtk_fixed_put (GTK_FIXED (fixed1), button_login_close, 456, 544);
  gtk_widget_set_size_request (button_login_close, 96, 29);

  image_login = create_pixmap (window_login, "mahiech finale_Plan de travail 1.png");
  gtk_widget_show (image_login);
  gtk_fixed_put (GTK_FIXED (fixed1), image_login, 0, 0);
  gtk_widget_set_size_request (image_login, 1024, 760);

  g_signal_connect ((gpointer) button_login_close, "clicked",
                    G_CALLBACK (on_button_login_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_password, "entry_login_password");
  GLADE_HOOKUP_OBJECT (window_login, entry_login_user, "entry_login_user");
  GLADE_HOOKUP_OBJECT (window_login, button_login_login, "button_login_login");
  GLADE_HOOKUP_OBJECT (window_login, button_login_close, "button_login_close");
  GLADE_HOOKUP_OBJECT (window_login, image_login, "image_login");

  return window_login;
}

GtkWidget*
create_window_employee (void)
{
  GtkWidget *window_employee;
  GtkWidget *fixed2;
  GtkWidget *button_gestion_ouvriers;
  GtkWidget *button_gestion_equipements;
  GtkWidget *button_gestion_clients;
  GtkWidget *button_calendrier;
  GtkWidget *button_gestion_capteurs;
  GtkWidget *button_gestion_troupeaux;

  window_employee = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_employee), 1);
  gtk_window_set_title (GTK_WINDOW (window_employee), _("Espace employ\303\251s"));
  gtk_window_set_default_size (GTK_WINDOW (window_employee), 1024, 745);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_employee), fixed2);

  button_gestion_ouvriers = gtk_button_new_with_mnemonic (_("Gestion des ouvriers"));
  gtk_widget_show (button_gestion_ouvriers);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_ouvriers, 581, 100);
  gtk_widget_set_size_request (button_gestion_ouvriers, 250, 100);

  button_gestion_equipements = gtk_button_new_with_mnemonic (_("Gestion des \303\251quipements"));
  gtk_widget_show (button_gestion_equipements);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_equipements, 197, 550);
  gtk_widget_set_size_request (button_gestion_equipements, 250, 100);

  button_gestion_clients = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (button_gestion_clients);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_clients, 581, 325);
  gtk_widget_set_size_request (button_gestion_clients, 250, 100);

  button_calendrier = gtk_button_new_with_mnemonic (_("Calendrier "));
  gtk_widget_show (button_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_calendrier, 581, 550);
  gtk_widget_set_size_request (button_calendrier, 250, 100);

  button_gestion_capteurs = gtk_button_new_with_mnemonic (_("Gestion des capteurs"));
  gtk_widget_show (button_gestion_capteurs);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_capteurs, 194, 100);
  gtk_widget_set_size_request (button_gestion_capteurs, 250, 100);

  button_gestion_troupeaux = gtk_button_new_with_mnemonic (_("Gestion des troupeaux"));
  gtk_widget_show (button_gestion_troupeaux);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gestion_troupeaux, 194, 325);
  gtk_widget_set_size_request (button_gestion_troupeaux, 250, 100);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_employee, window_employee, "window_employee");
  GLADE_HOOKUP_OBJECT (window_employee, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_ouvriers, "button_gestion_ouvriers");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_equipements, "button_gestion_equipements");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_clients, "button_gestion_clients");
  GLADE_HOOKUP_OBJECT (window_employee, button_calendrier, "button_calendrier");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_capteurs, "button_gestion_capteurs");
  GLADE_HOOKUP_OBJECT (window_employee, button_gestion_troupeaux, "button_gestion_troupeaux");

  return window_employee;
}

GtkWidget*
create_window1_gestion_capteurs (void)
{
  GtkWidget *window1_gestion_capteurs;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview4;
  GtkWidget *button6;
  GtkWidget *alignment7;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *button8;
  GtkWidget *alignment5;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *Capteur_temperature;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview5;
  GtkWidget *button10;
  GtkWidget *alignment9;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label13;
  GtkWidget *button9;
  GtkWidget *alignment10;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label14;
  GtkWidget *button11;
  GtkWidget *alignment8;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *label11;

  window1_gestion_capteurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_gestion_capteurs), _("gestion des capteurs"));
  gtk_window_set_default_size (GTK_WINDOW (window1_gestion_capteurs), 1024, 745);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1_gestion_capteurs), notebook1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow5, 168, 16);
  gtk_widget_set_size_request (scrolledwindow5, 888, 440);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview4);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed5), button6, 624, 456);
  gtk_widget_set_size_request (button6, 144, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button6), alignment7);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 768, 456);
  gtk_widget_set_size_request (button7, 144, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed5), button8, 912, 456);
  gtk_widget_set_size_request (button8, 152, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button8), alignment5);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  Capteur_temperature = gtk_label_new (_("capteurs temp\303\251rature"));
  gtk_widget_show (Capteur_temperature);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Capteur_temperature);
  gtk_misc_set_alignment (GTK_MISC (Capteur_temperature), 0.81, 0.54);
  gtk_misc_set_padding (GTK_MISC (Capteur_temperature), 200, 1);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow6, 184, 16);
  gtk_widget_set_size_request (scrolledwindow6, 896, 432);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview5);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 944, 456);
  gtk_widget_set_size_request (button10, 138, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button10), alignment9);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed6), button9, 805, 456);
  gtk_widget_set_size_request (button9, 138, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button9), alignment10);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 666, 456);
  gtk_widget_set_size_request (button11, 138, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button11), alignment8);
  gtk_widget_set_size_request (alignment8, 138, 17);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("capteurs_humidit\303\251"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label11);
  gtk_misc_set_padding (GTK_MISC (label11), 296, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_gestion_capteurs, window1_gestion_capteurs, "window1_gestion_capteurs");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, Capteur_temperature, "Capteur_temperature");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1_gestion_capteurs, label11, "label11");

  return window1_gestion_capteurs;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed7;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label20;
  GtkWidget *button13;
  GtkWidget *alignment11;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label18;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *entry3;
  GtkWidget *label15;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("Ajouter "));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window2), fixed7);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1, 144, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2, 144, 96);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label17 = gtk_label_new (_("marque :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed7), label17, 48, 56);
  gtk_widget_set_size_request (label17, 72, 24);

  label16 = gtk_label_new (_("R\303\251f\303\251rence :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed7), label16, 40, 104);
  gtk_widget_set_size_request (label16, 81, 17);

  spinbutton1_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton1, 176, 144);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton2, 240, 144);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton3, 304, 144);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label20 = gtk_label_new (_("d\303\251but de fonctionnemt :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed7), label20, 8, 144);
  gtk_widget_set_size_request (label20, 168, 24);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed7), button13, 56, 240);
  gtk_widget_set_size_request (button13, 96, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13), alignment11);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox9), label18, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed7), button12, 240, 240);
  gtk_widget_set_size_request (button12, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox10), label19, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("Valeur:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed7), label21, 24, 184);
  gtk_widget_set_size_request (label21, 88, 32);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3, 144, 184);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label15 = gtk_label_new (_("Ajouter un capteur :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed7), label15, 120, 16);
  gtk_widget_set_size_request (label15, 192, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window2, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window2, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, button13, "button13");
  GLADE_HOOKUP_OBJECT (window2, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window2, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window2, image9, "image9");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window2, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *_;
  GtkWidget *entry4;
  GtkWidget *label22;
  GtkWidget *button15;
  GtkWidget *alignment14;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label24;
  GtkWidget *button14;
  GtkWidget *alignment13;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label23;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("modifier"));

  _ = gtk_fixed_new ();
  gtk_widget_show (_);
  gtk_container_add (GTK_CONTAINER (window3), _);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (_), entry4, 160, 128);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label22 = gtk_label_new (_("nouvelle valeur :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (_), label22, 16, 128);
  gtk_widget_set_size_request (label22, 136, 32);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (_), button15, 256, 240);
  gtk_widget_set_size_request (button15, 96, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button15), alignment14);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox12), label24, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (_), button14, 32, 240);
  gtk_widget_set_size_request (button14, 104, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button14), alignment13);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("confimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, _, "_");
  GLADE_HOOKUP_OBJECT (window3, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3, button15, "button15");
  GLADE_HOOKUP_OBJECT (window3, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window3, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window3, image12, "image12");
  GLADE_HOOKUP_OBJECT (window3, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3, button14, "button14");
  GLADE_HOOKUP_OBJECT (window3, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window3, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window3, image11, "image11");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed9;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *button16;
  GtkWidget *alignment15;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label28;
  GtkWidget *button17;
  GtkWidget *alignment16;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label29;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("Supprimer"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window4), fixed9);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed9), entry5, 152, 64);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed9), entry6, 152, 112);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed9), entry7, 152, 168);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label25 = gtk_label_new (_("marque :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed9), label25, 24, 64);
  gtk_widget_set_size_request (label25, 81, 25);

  label26 = gtk_label_new (_("R\303\251f\303\251rence :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed9), label26, 32, 112);
  gtk_widget_set_size_request (label26, 81, 32);

  label27 = gtk_label_new (_("Valeur :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed9), label27, 24, 168);
  gtk_widget_set_size_request (label27, 80, 25);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed9), button16, 56, 248);
  gtk_widget_set_size_request (button16, 104, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button16), alignment15);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed9), button17, 264, 248);
  gtk_widget_set_size_request (button17, 96, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button17), alignment16);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox14), label29, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window4, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window4, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window4, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window4, label25, "label25");
  GLADE_HOOKUP_OBJECT (window4, label26, "label26");
  GLADE_HOOKUP_OBJECT (window4, label27, "label27");
  GLADE_HOOKUP_OBJECT (window4, button16, "button16");
  GLADE_HOOKUP_OBJECT (window4, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window4, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window4, image13, "image13");
  GLADE_HOOKUP_OBJECT (window4, label28, "label28");
  GLADE_HOOKUP_OBJECT (window4, button17, "button17");
  GLADE_HOOKUP_OBJECT (window4, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window4, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window4, image14, "image14");
  GLADE_HOOKUP_OBJECT (window4, label29, "label29");

  return window4;
}

