/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_login (void);
GtkWidget* create_window_employee (void);
GtkWidget* create_window1_gestion_capteurs (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
